/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`upload_image_options`]
#[derive(Clone, Debug)]
pub struct UploadImageOptionsParams {
    pub tenant_id: String
}


/// struct for typed errors of method [`upload_image_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadImageOptionsError {
    UnknownValue(serde_json::Value),
}


pub async fn upload_image_options(configuration: &configuration::Configuration, params: UploadImageOptionsParams) -> Result<String, Error<UploadImageOptionsError>> {

    let uri_str = format!("{}/upload-image/{tenantId}", configuration.base_path, tenantId=crate::apis::urlencode(params.tenant_id));
    let mut req_builder = configuration.client.request(reqwest::Method::OPTIONS, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<UploadImageOptionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

