/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockFromCommentParams {
    /// A list of comment ids to check if are blocked after performing the update.
    #[serde(rename = "commentIds", deserialize_with = "Option::deserialize")]
    pub comment_ids: Option<Vec<String>>,
}

impl BlockFromCommentParams {
    pub fn new(comment_ids: Option<Vec<String>>) -> BlockFromCommentParams {
        BlockFromCommentParams {
            comment_ids,
        }
    }
}

