/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckBlockedCommentsResponseAnyOf {
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "commentStatuses")]
    pub comment_statuses: std::collections::HashMap<String, bool>,
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
}

impl CheckBlockedCommentsResponseAnyOf {
    pub fn new(comment_statuses: std::collections::HashMap<String, bool>, status: models::ImportedApiStatusPeriodSuccess) -> CheckBlockedCommentsResponseAnyOf {
        CheckBlockedCommentsResponseAnyOf {
            comment_statuses,
            status,
        }
    }
}

