/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetComments200Response {
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<f64>,
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodFailed,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "comments")]
    pub comments: Vec<models::PublicComment>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<Box<models::UserSessionInfo>>,
    #[serde(rename = "urlIdClean", skip_serializing_if = "Option::is_none")]
    pub url_id_clean: Option<String>,
    #[serde(rename = "lastGenDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_gen_date: Option<Option<i32>>,
    #[serde(rename = "includesPastPages", skip_serializing_if = "Option::is_none")]
    pub includes_past_pages: Option<bool>,
    #[serde(rename = "isDemo", skip_serializing_if = "Option::is_none")]
    pub is_demo: Option<bool>,
    #[serde(rename = "commentCount", skip_serializing_if = "Option::is_none")]
    pub comment_count: Option<i32>,
    #[serde(rename = "isSiteAdmin", skip_serializing_if = "Option::is_none")]
    pub is_site_admin: Option<bool>,
    #[serde(rename = "hasBillingIssue", skip_serializing_if = "Option::is_none")]
    pub has_billing_issue: Option<bool>,
    #[serde(rename = "isCommentsHidden", skip_serializing_if = "Option::is_none")]
    pub is_comments_hidden: Option<bool>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "moduleData", skip_serializing_if = "Option::is_none")]
    pub module_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "pageNumber")]
    pub page_number: i32,
    #[serde(rename = "isWhiteLabeled", skip_serializing_if = "Option::is_none")]
    pub is_white_labeled: Option<bool>,
    #[serde(rename = "isProd", skip_serializing_if = "Option::is_none")]
    pub is_prod: Option<bool>,
    #[serde(rename = "isCrawler", skip_serializing_if = "Option::is_none")]
    pub is_crawler: Option<bool>,
    #[serde(rename = "notificationCount", skip_serializing_if = "Option::is_none")]
    pub notification_count: Option<i32>,
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "isClosed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    #[serde(rename = "presencePollState", skip_serializing_if = "Option::is_none")]
    pub presence_poll_state: Option<i32>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
    #[serde(rename = "urlIdWS", skip_serializing_if = "Option::is_none")]
    pub url_id_ws: Option<String>,
    #[serde(rename = "userIdWS", skip_serializing_if = "Option::is_none")]
    pub user_id_ws: Option<String>,
    #[serde(rename = "tenantIdWS", skip_serializing_if = "Option::is_none")]
    pub tenant_id_ws: Option<String>,
    #[serde(rename = "secondaryCode", skip_serializing_if = "Option::is_none")]
    pub secondary_code: Option<String>,
    #[serde(rename = "bannedUntil", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<f64>,
    #[serde(rename = "maxCharacterLength", skip_serializing_if = "Option::is_none")]
    pub max_character_length: Option<f64>,
    #[serde(rename = "translatedError", skip_serializing_if = "Option::is_none")]
    pub translated_error: Option<String>,
}

impl GetComments200Response {
    pub fn new(status: models::ImportedApiStatusPeriodFailed, code: String, reason: String, comments: Vec<models::PublicComment>, user: Option<models::UserSessionInfo>, page_number: i32) -> GetComments200Response {
        GetComments200Response {
            status_code: None,
            status,
            code,
            reason,
            comments,
            user: if let Some(x) = user {Some(Box::new(x))} else {None},
            url_id_clean: None,
            last_gen_date: None,
            includes_past_pages: None,
            is_demo: None,
            comment_count: None,
            is_site_admin: None,
            has_billing_issue: None,
            is_comments_hidden: None,
            module_data: None,
            page_number,
            is_white_labeled: None,
            is_prod: None,
            is_crawler: None,
            notification_count: None,
            has_more: None,
            is_closed: None,
            presence_poll_state: None,
            custom_config: None,
            url_id_ws: None,
            user_id_ws: None,
            tenant_id_ws: None,
            secondary_code: None,
            banned_until: None,
            max_character_length: None,
            translated_error: None,
        }
    }
}

