/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCommentVoteUserNamesSuccessResponse {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "voteUserNames")]
    pub vote_user_names: Vec<String>,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
}

impl GetCommentVoteUserNamesSuccessResponse {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess, vote_user_names: Vec<String>, has_more: bool) -> GetCommentVoteUserNamesSuccessResponse {
        GetCommentVoteUserNamesSuccessResponse {
            status,
            vote_user_names,
            has_more,
        }
    }
}

