/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GifRating {
    #[serde(rename = "g")]
    G,
    #[serde(rename = "pg")]
    Pg,
    #[serde(rename = "pg-13")]
    Pg13,
    #[serde(rename = "r")]
    R,

}

impl std::fmt::Display for GifRating {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::G => write!(f, "g"),
            Self::Pg => write!(f, "pg"),
            Self::Pg13 => write!(f, "pg-13"),
            Self::R => write!(f, "r"),
        }
    }
}

impl Default for GifRating {
    fn default() -> GifRating {
        Self::G
    }
}

