/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeaderState {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "NotificationType")]
    pub notification_type: serde_json::Value,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIdWS")]
    pub user_id_ws: String,
    #[serde(rename = "notificationCounts")]
    pub notification_counts: Vec<models::NotificationAndCount>,
}

impl HeaderState {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess, notification_type: serde_json::Value, user_id: String, user_id_ws: String, notification_counts: Vec<models::NotificationAndCount>) -> HeaderState {
        HeaderState {
            status,
            notification_type,
            user_id,
            user_id_ws,
            notification_counts,
        }
    }
}

