/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PickFCommentPeriodApprovedOrCommentHtml : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickFCommentPeriodApprovedOrCommentHtml {
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
}

impl PickFCommentPeriodApprovedOrCommentHtml {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(approved: bool, comment_html: String) -> PickFCommentPeriodApprovedOrCommentHtml {
        PickFCommentPeriodApprovedOrCommentHtml {
            approved,
            comment_html,
        }
    }
}

