/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicComment {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterLink", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<String>,
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<i32>,
    #[serde(rename = "votesUp", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<i32>,
    #[serde(rename = "votesDown", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<i32>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "avatarSrc", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<String>,
    #[serde(rename = "hasImages", skip_serializing_if = "Option::is_none")]
    pub has_images: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<bool>,
    #[serde(rename = "isLocked", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<bool>,
    #[serde(rename = "displayLabel", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<String>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    #[serde(rename = "badges", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Vec<models::CommentUserBadgeInfo>>,
    #[serde(rename = "viewCount", skip_serializing_if = "Option::is_none")]
    pub view_count: Option<f64>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "anonUserId", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<String>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    #[serde(rename = "isUnread", skip_serializing_if = "Option::is_none")]
    pub is_unread: Option<bool>,
    #[serde(rename = "myVoteId", skip_serializing_if = "Option::is_none")]
    pub my_vote_id: Option<String>,
    #[serde(rename = "isVotedDown", skip_serializing_if = "Option::is_none")]
    pub is_voted_down: Option<bool>,
    #[serde(rename = "isVotedUp", skip_serializing_if = "Option::is_none")]
    pub is_voted_up: Option<bool>,
    /// This is always set when asTree=true
    #[serde(rename = "hasChildren", skip_serializing_if = "Option::is_none")]
    pub has_children: Option<bool>,
    /// The total nested child count included in this response (may be more available w/ pagination) Only set with asTree=true, otherwise this will be null.
    #[serde(rename = "nestedChildrenCount", skip_serializing_if = "Option::is_none")]
    pub nested_children_count: Option<i32>,
    /// You must ask the API to count children (with asTree=true&countChildren=true), otherwise this will be null. This will be the complete direct child count, whereas children may only contain a subset based on pagination.
    #[serde(rename = "childCount", skip_serializing_if = "Option::is_none")]
    pub child_count: Option<i32>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::PublicComment>>,
    #[serde(rename = "isFlagged", skip_serializing_if = "Option::is_none")]
    pub is_flagged: Option<bool>,
    #[serde(rename = "isBlocked", skip_serializing_if = "Option::is_none")]
    pub is_blocked: Option<bool>,
}

impl PublicComment {
    pub fn new(_id: String, comment_html: String, commenter_name: String, date: String, verified: bool) -> PublicComment {
        PublicComment {
            _id,
            comment_html,
            user_id: None,
            commenter_name,
            commenter_link: None,
            parent_id: None,
            date,
            votes: None,
            votes_up: None,
            votes_down: None,
            verified,
            avatar_src: None,
            has_images: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            display_label: None,
            rating: None,
            badges: None,
            view_count: None,
            is_deleted: None,
            is_deleted_user: None,
            is_spam: None,
            anon_user_id: None,
            feedback_ids: None,
            is_unread: None,
            my_vote_id: None,
            is_voted_down: None,
            is_voted_up: None,
            has_children: None,
            nested_children_count: None,
            child_count: None,
            children: None,
            is_flagged: None,
            is_blocked: None,
        }
    }
}

