/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// AggregationRequest : The aggregation request accepts a resource, optional grouping keys, an array of operations, and an optional sort
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregationRequest {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Vec<models::QueryPredicate>>,
    #[serde(rename = "resourceName")]
    pub resource_name: String,
    #[serde(rename = "groupBy", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<String>>,
    #[serde(rename = "operations")]
    pub operations: Vec<models::AggregationOperation>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::AggregationRequestSort>>,
}

impl AggregationRequest {
    /// The aggregation request accepts a resource, optional grouping keys, an array of operations, and an optional sort
    pub fn new(resource_name: String, operations: Vec<models::AggregationOperation>) -> AggregationRequest {
        AggregationRequest {
            query: None,
            resource_name,
            group_by: None,
            operations,
            sort: None,
        }
    }
}

