/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregationItem {
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<std::collections::HashMap<String, String>>,
}

impl AggregationItem {
    pub fn new() -> AggregationItem {
        AggregationItem {
            groups: None,
        }
    }
}

