/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiModerateUserBanPreferences {
    #[serde(rename = "shouldBanEmail")]
    pub should_ban_email: bool,
    #[serde(rename = "shouldBanByIP")]
    pub should_ban_by_ip: bool,
    #[serde(rename = "lastBanType")]
    pub last_ban_type: String,
    #[serde(rename = "lastBanDuration")]
    pub last_ban_duration: String,
}

impl ApiModerateUserBanPreferences {
    pub fn new(should_ban_email: bool, should_ban_by_ip: bool, last_ban_type: String, last_ban_duration: String) -> ApiModerateUserBanPreferences {
        ApiModerateUserBanPreferences {
            should_ban_email,
            should_ban_by_ip,
            last_ban_type,
            last_ban_duration,
        }
    }
}

