/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiCommentBase {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "aiDeterminedSpam", skip_serializing_if = "Option::is_none")]
    pub ai_determined_spam: Option<bool>,
    #[serde(rename = "anonUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<Option<String>>,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "badges", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Option<Vec<models::CommentUserBadgeInfo>>>,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "commenterEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<Option<String>>,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "date", deserialize_with = "Option::deserialize")]
    pub date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "displayLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<Option<String>>,
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "externalParentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_parent_id: Option<Option<String>>,
    #[serde(rename = "expireAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    #[serde(rename = "flagCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_count: Option<Option<i32>>,
    #[serde(rename = "fromProductId", skip_serializing_if = "Option::is_none")]
    pub from_product_id: Option<i32>,
    #[serde(rename = "hasCode", skip_serializing_if = "Option::is_none")]
    pub has_code: Option<bool>,
    #[serde(rename = "hasImages", skip_serializing_if = "Option::is_none")]
    pub has_images: Option<bool>,
    #[serde(rename = "hasLinks", skip_serializing_if = "Option::is_none")]
    pub has_links: Option<bool>,
    #[serde(rename = "hashTags", skip_serializing_if = "Option::is_none")]
    pub hash_tags: Option<Vec<models::CommentUserHashTagInfo>>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isPinned", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<Option<bool>>,
    #[serde(rename = "isLocked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<Option<bool>>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "localDateHours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_hours: Option<Option<i32>>,
    #[serde(rename = "localDateString", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<Option<String>>,
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<String>,
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<models::CommentUserMentionInfo>>,
    #[serde(rename = "meta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Option<models::ApiCommentBaseMeta>>,
    #[serde(rename = "moderationGroupIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "notificationSentForParent", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent: Option<bool>,
    #[serde(rename = "notificationSentForParentTenant", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent_tenant: Option<bool>,
    #[serde(rename = "pageTitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<Option<String>>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<f64>>,
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "urlIdRaw", skip_serializing_if = "Option::is_none")]
    pub url_id_raw: Option<String>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "verifiedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verified_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "votes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Option<i32>>,
    #[serde(rename = "votesDown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<Option<i32>>,
    #[serde(rename = "votesUp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<Option<i32>>,
}

impl ApiCommentBase {
    pub fn new(id: String, approved: bool, comment: String, comment_html: String, commenter_name: String, date: Option<chrono::DateTime<chrono::FixedOffset>>, locale: Option<String>, tenant_id: String, url: String, url_id: String, verified: bool) -> ApiCommentBase {
        ApiCommentBase {
            id,
            ai_determined_spam: None,
            anon_user_id: None,
            approved,
            avatar_src: None,
            badges: None,
            comment,
            comment_html,
            commenter_email: None,
            commenter_link: None,
            commenter_name,
            date,
            display_label: None,
            domain: None,
            external_id: None,
            external_parent_id: None,
            expire_at: None,
            feedback_ids: None,
            flag_count: None,
            from_product_id: None,
            has_code: None,
            has_images: None,
            has_links: None,
            hash_tags: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_deleted: None,
            is_deleted_user: None,
            is_pinned: None,
            is_locked: None,
            is_spam: None,
            local_date_hours: None,
            local_date_string: None,
            locale,
            mentions: None,
            meta: None,
            moderation_group_ids: None,
            notification_sent_for_parent: None,
            notification_sent_for_parent_tenant: None,
            page_title: None,
            parent_id: None,
            rating: None,
            reviewed: None,
            tenant_id,
            url,
            url_id,
            url_id_raw: None,
            user_id: None,
            verified,
            verified_date: None,
            votes: None,
            votes_down: None,
            votes_up: None,
        }
    }
}

