/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBanUserChangedValues {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub username: Option<Option<String>>,
    #[serde(rename = "ipHash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_hash: Option<Option<String>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "bannedByUserId", skip_serializing_if = "Option::is_none")]
    pub banned_by_user_id: Option<String>,
    #[serde(rename = "bannedCommentText", skip_serializing_if = "Option::is_none")]
    pub banned_comment_text: Option<String>,
    #[serde(rename = "banType", skip_serializing_if = "Option::is_none")]
    pub ban_type: Option<String>,
    #[serde(rename = "bannedUntil", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "hasEmailWildcard", skip_serializing_if = "Option::is_none")]
    pub has_email_wildcard: Option<bool>,
    #[serde(rename = "banReason", skip_serializing_if = "Option::is_none")]
    pub ban_reason: Option<String>,
}

impl ApiBanUserChangedValues {
    pub fn new() -> ApiBanUserChangedValues {
        ApiBanUserChangedValues {
            _id: None,
            tenant_id: None,
            user_id: None,
            email: None,
            username: None,
            ip_hash: None,
            created_at: None,
            banned_by_user_id: None,
            banned_comment_text: None,
            ban_type: None,
            banned_until: None,
            has_email_wildcard: None,
            ban_reason: None,
        }
    }
}

