/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetUserBadgeProgressListResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "userBadgeProgresses")]
    pub user_badge_progresses: Vec<models::UserBadgeProgress>,
}

impl ApiGetUserBadgeProgressListResponse {
    pub fn new(status: models::ApiStatus, user_badge_progresses: Vec<models::UserBadgeProgress>) -> ApiGetUserBadgeProgressListResponse {
        ApiGetUserBadgeProgressListResponse {
            status,
            user_badge_progresses,
        }
    }
}

