/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetCommentResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "comment")]
    pub comment: Box<models::PickFCommentPeriodApiCommentFieldsKeys>,
}

impl ApiGetCommentResponse {
    pub fn new(status: models::ApiStatus, comment: models::PickFCommentPeriodApiCommentFieldsKeys) -> ApiGetCommentResponse {
        ApiGetCommentResponse {
            status,
            comment: Box::new(comment),
        }
    }
}

