/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetUserBadgeResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "userBadge")]
    pub user_badge: Box<models::UserBadge>,
}

impl ApiGetUserBadgeResponse {
    pub fn new(status: models::ApiStatus, user_badge: models::UserBadge) -> ApiGetUserBadgeResponse {
        ApiGetUserBadgeResponse {
            status,
            user_badge: Box::new(user_badge),
        }
    }
}

