/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTenant {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "signUpDate")]
    pub sign_up_date: f64,
    #[serde(rename = "packageId")]
    pub package_id: String,
    #[serde(rename = "paymentFrequency")]
    pub payment_frequency: f64,
    #[serde(rename = "billingInfoValid")]
    pub billing_info_valid: bool,
    #[serde(rename = "billingHandledExternally", skip_serializing_if = "Option::is_none")]
    pub billing_handled_externally: Option<bool>,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "isSetup")]
    pub is_setup: bool,
    #[serde(rename = "domainConfiguration")]
    pub domain_configuration: Vec<models::ApiDomainConfiguration>,
    #[serde(rename = "billingInfo", skip_serializing_if = "Option::is_none")]
    pub billing_info: Option<Box<models::BillingInfo>>,
    #[serde(rename = "stripeCustomerId", skip_serializing_if = "Option::is_none")]
    pub stripe_customer_id: Option<String>,
    #[serde(rename = "stripeSubscriptionId", skip_serializing_if = "Option::is_none")]
    pub stripe_subscription_id: Option<String>,
    #[serde(rename = "stripePlanId", skip_serializing_if = "Option::is_none")]
    pub stripe_plan_id: Option<String>,
    #[serde(rename = "enableProfanityFilter")]
    pub enable_profanity_filter: bool,
    #[serde(rename = "enableSpamFilter")]
    pub enable_spam_filter: bool,
    #[serde(rename = "lastBillingIssueReminderDate", skip_serializing_if = "Option::is_none")]
    pub last_billing_issue_reminder_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "removeUnverifiedComments", skip_serializing_if = "Option::is_none")]
    pub remove_unverified_comments: Option<bool>,
    #[serde(rename = "unverifiedCommentsTTLms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unverified_comments_tt_lms: Option<Option<f64>>,
    #[serde(rename = "commentsRequireApproval", skip_serializing_if = "Option::is_none")]
    pub comments_require_approval: Option<bool>,
    #[serde(rename = "autoApproveCommentOnVerification", skip_serializing_if = "Option::is_none")]
    pub auto_approve_comment_on_verification: Option<bool>,
    #[serde(rename = "sendProfaneToSpam", skip_serializing_if = "Option::is_none")]
    pub send_profane_to_spam: Option<bool>,
    #[serde(rename = "hasFlexPricing", skip_serializing_if = "Option::is_none")]
    pub has_flex_pricing: Option<bool>,
    #[serde(rename = "hasAuditing", skip_serializing_if = "Option::is_none")]
    pub has_auditing: Option<bool>,
    #[serde(rename = "flexLastBilledAmount", skip_serializing_if = "Option::is_none")]
    pub flex_last_billed_amount: Option<f64>,
    #[serde(rename = "deAnonIpAddr", skip_serializing_if = "Option::is_none")]
    pub de_anon_ip_addr: Option<f64>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, String>>,
}

impl ApiTenant {
    pub fn new(id: String, name: String, sign_up_date: f64, package_id: String, payment_frequency: f64, billing_info_valid: bool, created_by: String, is_setup: bool, domain_configuration: Vec<models::ApiDomainConfiguration>, enable_profanity_filter: bool, enable_spam_filter: bool) -> ApiTenant {
        ApiTenant {
            id,
            name,
            email: None,
            sign_up_date,
            package_id,
            payment_frequency,
            billing_info_valid,
            billing_handled_externally: None,
            created_by,
            is_setup,
            domain_configuration,
            billing_info: None,
            stripe_customer_id: None,
            stripe_subscription_id: None,
            stripe_plan_id: None,
            enable_profanity_filter,
            enable_spam_filter,
            last_billing_issue_reminder_date: None,
            remove_unverified_comments: None,
            unverified_comments_tt_lms: None,
            comments_require_approval: None,
            auto_approve_comment_on_verification: None,
            send_profane_to_spam: None,
            has_flex_pricing: None,
            has_auditing: None,
            flex_last_billed_amount: None,
            de_anon_ip_addr: None,
            meta: None,
        }
    }
}

