/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTicketFile {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "s3Key")]
    pub s3_key: String,
    #[serde(rename = "originalFileName")]
    pub original_file_name: String,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: i32,
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "uploadedByUserId")]
    pub uploaded_by_user_id: String,
    #[serde(rename = "uploadedAt")]
    pub uploaded_at: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "expired", skip_serializing_if = "Option::is_none")]
    pub expired: Option<bool>,
}

impl ApiTicketFile {
    pub fn new(id: String, s3_key: String, original_file_name: String, size_bytes: i32, content_type: String, uploaded_by_user_id: String, uploaded_at: String, url: String, expires_at: String) -> ApiTicketFile {
        ApiTicketFile {
            id,
            s3_key,
            original_file_name,
            size_bytes,
            content_type,
            uploaded_by_user_id,
            uploaded_at,
            url,
            expires_at,
            expired: None,
        }
    }
}

