/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiModerateGetUserBanPreferencesResponse {
    #[serde(rename = "preferences", deserialize_with = "Option::deserialize")]
    pub preferences: Option<Box<models::ApiModerateUserBanPreferences>>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl ApiModerateGetUserBanPreferencesResponse {
    pub fn new(preferences: Option<models::ApiModerateUserBanPreferences>, status: models::ApiStatus) -> ApiModerateGetUserBanPreferencesResponse {
        ApiModerateGetUserBanPreferencesResponse {
            preferences: if let Some(x) = preferences {Some(Box::new(x))} else {None},
            status,
        }
    }
}

