/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetUserBadgeProgressResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "userBadgeProgress")]
    pub user_badge_progress: Box<models::UserBadgeProgress>,
}

impl ApiGetUserBadgeProgressResponse {
    pub fn new(status: models::ApiStatus, user_badge_progress: models::UserBadgeProgress) -> ApiGetUserBadgeProgressResponse {
        ApiGetUserBadgeProgressResponse {
            status,
            user_badge_progress: Box::new(user_badge_progress),
        }
    }
}

