/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BannedUserMatchType {
    #[serde(rename = "userId")]
    UserId,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "email-wildcard")]
    EmailWildcard,
    #[serde(rename = "IP")]
    Ip,

}

impl std::fmt::Display for BannedUserMatchType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserId => write!(f, "userId"),
            Self::Email => write!(f, "email"),
            Self::EmailWildcard => write!(f, "email-wildcard"),
            Self::Ip => write!(f, "IP"),
        }
    }
}

impl Default for BannedUserMatchType {
    fn default() -> BannedUserMatchType {
        Self::UserId
    }
}

