/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockFromCommentParams {
    #[serde(rename = "commentIdsToCheck", skip_serializing_if = "Option::is_none")]
    pub comment_ids_to_check: Option<Vec<String>>,
}

impl BlockFromCommentParams {
    pub fn new() -> BlockFromCommentParams {
        BlockFromCommentParams {
            comment_ids_to_check: None,
        }
    }
}

