/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildModerationFilterResponse {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "moderationFilter")]
    pub moderation_filter: Box<models::ModerationFilter>,
}

impl BuildModerationFilterResponse {
    pub fn new(status: String, moderation_filter: models::ModerationFilter) -> BuildModerationFilterResponse {
        BuildModerationFilterResponse {
            status,
            moderation_filter: Box::new(moderation_filter),
        }
    }
}

