/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkCreateHashTagsBody {
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    #[serde(rename = "tags")]
    pub tags: Vec<models::BulkCreateHashTagsBodyTagsInner>,
}

impl BulkCreateHashTagsBody {
    pub fn new(tags: Vec<models::BulkCreateHashTagsBodyTagsInner>) -> BulkCreateHashTagsBody {
        BulkCreateHashTagsBody {
            tenant_id: None,
            tags,
        }
    }
}

