/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkAggregateQuestionItem {
    #[serde(rename = "aggId")]
    pub agg_id: String,
    #[serde(rename = "questionId", skip_serializing_if = "Option::is_none")]
    pub question_id: Option<String>,
    #[serde(rename = "questionIds", skip_serializing_if = "Option::is_none")]
    pub question_ids: Option<Vec<String>>,
    #[serde(rename = "urlId", skip_serializing_if = "Option::is_none")]
    pub url_id: Option<String>,
    #[serde(rename = "timeBucket", skip_serializing_if = "Option::is_none")]
    pub time_bucket: Option<models::AggregateTimeBucket>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
}

impl BulkAggregateQuestionItem {
    pub fn new(agg_id: String) -> BulkAggregateQuestionItem {
        BulkAggregateQuestionItem {
            agg_id,
            question_id: None,
            question_ids: None,
            url_id: None,
            time_bucket: None,
            start_date: None,
        }
    }
}

