/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkPreBanSummary {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "totalRelatedCommentCount")]
    pub total_related_comment_count: i32,
    #[serde(rename = "emailDomains")]
    pub email_domains: Vec<String>,
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
    #[serde(rename = "ipHashes")]
    pub ip_hashes: Vec<String>,
}

impl BulkPreBanSummary {
    pub fn new(status: String, total_related_comment_count: i32, email_domains: Vec<String>, emails: Vec<String>, user_ids: Vec<String>, ip_hashes: Vec<String>) -> BulkPreBanSummary {
        BulkPreBanSummary {
            status,
            total_related_comment_count,
            email_domains,
            emails,
            user_ids,
            ip_hashes,
        }
    }
}

