/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkPreBanParams {
    #[serde(rename = "commentIds")]
    pub comment_ids: Vec<String>,
}

impl BulkPreBanParams {
    pub fn new(comment_ids: Vec<String>) -> BulkPreBanParams {
        BulkPreBanParams {
            comment_ids,
        }
    }
}

