/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeTicketStateBody {
    #[serde(rename = "state")]
    pub state: i32,
}

impl ChangeTicketStateBody {
    pub fn new(state: i32) -> ChangeTicketStateBody {
        ChangeTicketStateBody {
            state,
        }
    }
}

