/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckedCommentsForBlocked200Response {
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "commentStatuses")]
    pub comment_statuses: std::collections::HashMap<String, bool>,
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodFailed,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<f64>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "secondaryCode", skip_serializing_if = "Option::is_none")]
    pub secondary_code: Option<String>,
    #[serde(rename = "bannedUntil", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<f64>,
    #[serde(rename = "maxCharacterLength", skip_serializing_if = "Option::is_none")]
    pub max_character_length: Option<f64>,
    #[serde(rename = "translatedError", skip_serializing_if = "Option::is_none")]
    pub translated_error: Option<String>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
}

impl CheckedCommentsForBlocked200Response {
    pub fn new(comment_statuses: std::collections::HashMap<String, bool>, status: models::ImportedApiStatusPeriodFailed, reason: String, code: String) -> CheckedCommentsForBlocked200Response {
        CheckedCommentsForBlocked200Response {
            comment_statuses,
            status,
            status_code: None,
            reason,
            code,
            secondary_code: None,
            banned_until: None,
            max_character_length: None,
            translated_error: None,
            custom_config: None,
        }
    }
}

