/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentUserHashTagInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<String>,
    #[serde(rename = "retain", skip_serializing_if = "Option::is_none")]
    pub retain: Option<bool>,
}

impl CommentUserHashTagInfo {
    pub fn new(id: String, tag: String, url: Option<String>) -> CommentUserHashTagInfo {
        CommentUserHashTagInfo {
            id,
            tag,
            url,
            retain: None,
        }
    }
}

