/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentUserBadgeInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: f64,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "displayLabel", deserialize_with = "Option::deserialize")]
    pub display_label: Option<String>,
    #[serde(rename = "displaySrc", deserialize_with = "Option::deserialize")]
    pub display_src: Option<String>,
    #[serde(rename = "backgroundColor", deserialize_with = "Option::deserialize")]
    pub background_color: Option<String>,
    #[serde(rename = "borderColor", deserialize_with = "Option::deserialize")]
    pub border_color: Option<String>,
    #[serde(rename = "textColor", deserialize_with = "Option::deserialize")]
    pub text_color: Option<String>,
    #[serde(rename = "cssClass", deserialize_with = "Option::deserialize")]
    pub css_class: Option<String>,
}

impl CommentUserBadgeInfo {
    pub fn new(id: String, r#type: f64, description: String, display_label: Option<String>, display_src: Option<String>, background_color: Option<String>, border_color: Option<String>, text_color: Option<String>, css_class: Option<String>) -> CommentUserBadgeInfo {
        CommentUserBadgeInfo {
            id,
            r#type,
            description,
            display_label,
            display_src,
            background_color,
            border_color,
            text_color,
            css_class,
        }
    }
}

