/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CommentLogType {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "7")]
    Variant7,
    #[serde(rename = "8")]
    Variant8,
    #[serde(rename = "9")]
    Variant9,
    #[serde(rename = "10")]
    Variant10,
    #[serde(rename = "11")]
    Variant11,
    #[serde(rename = "12")]
    Variant12,
    #[serde(rename = "13")]
    Variant13,
    #[serde(rename = "14")]
    Variant14,
    #[serde(rename = "15")]
    Variant15,
    #[serde(rename = "16")]
    Variant16,
    #[serde(rename = "17")]
    Variant17,
    #[serde(rename = "18")]
    Variant18,
    #[serde(rename = "19")]
    Variant19,
    #[serde(rename = "20")]
    Variant20,
    #[serde(rename = "21")]
    Variant21,
    #[serde(rename = "22")]
    Variant22,
    #[serde(rename = "23")]
    Variant23,
    #[serde(rename = "24")]
    Variant24,
    #[serde(rename = "25")]
    Variant25,
    #[serde(rename = "26")]
    Variant26,
    #[serde(rename = "27")]
    Variant27,
    #[serde(rename = "28")]
    Variant28,
    #[serde(rename = "29")]
    Variant29,
    #[serde(rename = "30")]
    Variant30,
    #[serde(rename = "31")]
    Variant31,
    #[serde(rename = "32")]
    Variant32,
    #[serde(rename = "33")]
    Variant33,
    #[serde(rename = "34")]
    Variant34,
    #[serde(rename = "35")]
    Variant35,
    #[serde(rename = "36")]
    Variant36,
    #[serde(rename = "37")]
    Variant37,
    #[serde(rename = "38")]
    Variant38,
    #[serde(rename = "39")]
    Variant39,
    #[serde(rename = "40")]
    Variant40,
    #[serde(rename = "41")]
    Variant41,
    #[serde(rename = "42")]
    Variant42,
    #[serde(rename = "43")]
    Variant43,
    #[serde(rename = "44")]
    Variant44,
    #[serde(rename = "45")]
    Variant45,
    #[serde(rename = "46")]
    Variant46,
    #[serde(rename = "47")]
    Variant47,
    #[serde(rename = "48")]
    Variant48,
    #[serde(rename = "49")]
    Variant49,
    #[serde(rename = "50")]
    Variant50,
    #[serde(rename = "51")]
    Variant51,
    #[serde(rename = "52")]
    Variant52,
    #[serde(rename = "53")]
    Variant53,
    #[serde(rename = "54")]
    Variant54,

}

impl std::fmt::Display for CommentLogType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant0 => write!(f, "0"),
            Self::Variant1 => write!(f, "1"),
            Self::Variant2 => write!(f, "2"),
            Self::Variant3 => write!(f, "3"),
            Self::Variant4 => write!(f, "4"),
            Self::Variant5 => write!(f, "5"),
            Self::Variant6 => write!(f, "6"),
            Self::Variant7 => write!(f, "7"),
            Self::Variant8 => write!(f, "8"),
            Self::Variant9 => write!(f, "9"),
            Self::Variant10 => write!(f, "10"),
            Self::Variant11 => write!(f, "11"),
            Self::Variant12 => write!(f, "12"),
            Self::Variant13 => write!(f, "13"),
            Self::Variant14 => write!(f, "14"),
            Self::Variant15 => write!(f, "15"),
            Self::Variant16 => write!(f, "16"),
            Self::Variant17 => write!(f, "17"),
            Self::Variant18 => write!(f, "18"),
            Self::Variant19 => write!(f, "19"),
            Self::Variant20 => write!(f, "20"),
            Self::Variant21 => write!(f, "21"),
            Self::Variant22 => write!(f, "22"),
            Self::Variant23 => write!(f, "23"),
            Self::Variant24 => write!(f, "24"),
            Self::Variant25 => write!(f, "25"),
            Self::Variant26 => write!(f, "26"),
            Self::Variant27 => write!(f, "27"),
            Self::Variant28 => write!(f, "28"),
            Self::Variant29 => write!(f, "29"),
            Self::Variant30 => write!(f, "30"),
            Self::Variant31 => write!(f, "31"),
            Self::Variant32 => write!(f, "32"),
            Self::Variant33 => write!(f, "33"),
            Self::Variant34 => write!(f, "34"),
            Self::Variant35 => write!(f, "35"),
            Self::Variant36 => write!(f, "36"),
            Self::Variant37 => write!(f, "37"),
            Self::Variant38 => write!(f, "38"),
            Self::Variant39 => write!(f, "39"),
            Self::Variant40 => write!(f, "40"),
            Self::Variant41 => write!(f, "41"),
            Self::Variant42 => write!(f, "42"),
            Self::Variant43 => write!(f, "43"),
            Self::Variant44 => write!(f, "44"),
            Self::Variant45 => write!(f, "45"),
            Self::Variant46 => write!(f, "46"),
            Self::Variant47 => write!(f, "47"),
            Self::Variant48 => write!(f, "48"),
            Self::Variant49 => write!(f, "49"),
            Self::Variant50 => write!(f, "50"),
            Self::Variant51 => write!(f, "51"),
            Self::Variant52 => write!(f, "52"),
            Self::Variant53 => write!(f, "53"),
            Self::Variant54 => write!(f, "54"),
        }
    }
}

impl Default for CommentLogType {
    fn default() -> CommentLogType {
        Self::Variant0
    }
}

