/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentData {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<i64>,
    #[serde(rename = "localDateString", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<String>,
    #[serde(rename = "localDateHours", skip_serializing_if = "Option::is_none")]
    pub local_date_hours: Option<i32>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<Option<String>>,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<i32>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<models::CommentUserMentionInfo>>,
    #[serde(rename = "hashTags", skip_serializing_if = "Option::is_none")]
    pub hash_tags: Option<Vec<models::CommentUserHashTagInfo>>,
    #[serde(rename = "pageTitle", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<String>,
    #[serde(rename = "isFromMyAccountPage", skip_serializing_if = "Option::is_none")]
    pub is_from_my_account_page: Option<bool>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    #[serde(rename = "moderationGroupIds", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Vec<String>>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    #[serde(rename = "fromOfflineRestore", skip_serializing_if = "Option::is_none")]
    pub from_offline_restore: Option<bool>,
    #[serde(rename = "autoplayDelayMS", skip_serializing_if = "Option::is_none")]
    pub autoplay_delay_ms: Option<i64>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "questionValues", skip_serializing_if = "Option::is_none")]
    pub question_values: Option<std::collections::HashMap<String, models::RecordStringStringOrNumberValue>>,
}

impl CommentData {
    pub fn new(commenter_name: String, comment: String, url: String, url_id: String) -> CommentData {
        CommentData {
            date: None,
            local_date_string: None,
            local_date_hours: None,
            commenter_name,
            commenter_email: None,
            commenter_link: None,
            comment,
            product_id: None,
            user_id: None,
            avatar_src: None,
            parent_id: None,
            mentions: None,
            hash_tags: None,
            page_title: None,
            is_from_my_account_page: None,
            url,
            url_id,
            meta: None,
            moderation_group_ids: None,
            rating: None,
            from_offline_restore: None,
            autoplay_delay_ms: None,
            feedback_ids: None,
            question_values: None,
        }
    }
}

