/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateModeratorResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "moderator")]
    pub moderator: Box<models::Moderator>,
}

impl CreateModeratorResponse {
    pub fn new(status: models::ApiStatus, moderator: models::Moderator) -> CreateModeratorResponse {
        CreateModeratorResponse {
            status,
            moderator: Box::new(moderator),
        }
    }
}

