/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVoteResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl CreateVoteResponse {
    pub fn new(status: models::ApiStatus) -> CreateVoteResponse {
        CreateVoteResponse {
            status,
        }
    }
}

