/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHashTagResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "hashTag")]
    pub hash_tag: Box<models::TenantHashTag>,
}

impl CreateHashTagResponse {
    pub fn new(status: models::ApiStatus, hash_tag: models::TenantHashTag) -> CreateHashTagResponse {
        CreateHashTagResponse {
            status,
            hash_tag: Box::new(hash_tag),
        }
    }
}

