/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTenantPackageResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "tenantPackage")]
    pub tenant_package: Box<models::TenantPackage>,
}

impl CreateTenantPackageResponse {
    pub fn new(status: models::ApiStatus, tenant_package: models::TenantPackage) -> CreateTenantPackageResponse {
        CreateTenantPackageResponse {
            status,
            tenant_package: Box::new(tenant_package),
        }
    }
}

