/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEmailTemplateBody {
    #[serde(rename = "emailTemplateId")]
    pub email_template_id: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "ejs")]
    pub ejs: String,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "translationOverridesByLocale", skip_serializing_if = "Option::is_none")]
    pub translation_overrides_by_locale: Option<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "testData", skip_serializing_if = "Option::is_none")]
    pub test_data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CreateEmailTemplateBody {
    pub fn new(email_template_id: String, display_name: String, ejs: String) -> CreateEmailTemplateBody {
        CreateEmailTemplateBody {
            email_template_id,
            display_name,
            ejs,
            domain: None,
            translation_overrides_by_locale: None,
            test_data: None,
        }
    }
}

