/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateQuestionConfigBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "question")]
    pub question: String,
    #[serde(rename = "helpText", skip_serializing_if = "Option::is_none")]
    pub help_text: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "numStars", skip_serializing_if = "Option::is_none")]
    pub num_stars: Option<f64>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<f64>,
    #[serde(rename = "labelNegative", skip_serializing_if = "Option::is_none")]
    pub label_negative: Option<String>,
    #[serde(rename = "labelPositive", skip_serializing_if = "Option::is_none")]
    pub label_positive: Option<String>,
    #[serde(rename = "customOptions", skip_serializing_if = "Option::is_none")]
    pub custom_options: Option<Vec<models::QuestionConfigCustomOptionsInner>>,
    #[serde(rename = "subQuestionIds", skip_serializing_if = "Option::is_none")]
    pub sub_question_ids: Option<Vec<String>>,
    #[serde(rename = "alwaysShowSubQuestions", skip_serializing_if = "Option::is_none")]
    pub always_show_sub_questions: Option<bool>,
    #[serde(rename = "reportingOrder")]
    pub reporting_order: f64,
}

impl CreateQuestionConfigBody {
    pub fn new(name: String, question: String, r#type: String, reporting_order: f64) -> CreateQuestionConfigBody {
        CreateQuestionConfigBody {
            name,
            question,
            help_text: None,
            r#type,
            num_stars: None,
            min: None,
            max: None,
            default_value: None,
            label_negative: None,
            label_positive: None,
            custom_options: None,
            sub_question_ids: None,
            always_show_sub_questions: None,
            reporting_order,
        }
    }
}

