/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCommentPublic200Response {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodFailed,
    #[serde(rename = "comment")]
    pub comment: Box<models::PublicComment>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<Box<models::UserSessionInfo>>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "moduleData", skip_serializing_if = "Option::is_none")]
    pub module_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "userIdWS", skip_serializing_if = "Option::is_none")]
    pub user_id_ws: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "secondaryCode", skip_serializing_if = "Option::is_none")]
    pub secondary_code: Option<String>,
    #[serde(rename = "bannedUntil", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<f64>,
    #[serde(rename = "maxCharacterLength", skip_serializing_if = "Option::is_none")]
    pub max_character_length: Option<f64>,
    #[serde(rename = "translatedError", skip_serializing_if = "Option::is_none")]
    pub translated_error: Option<String>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
}

impl CreateCommentPublic200Response {
    pub fn new(status: models::ImportedApiStatusPeriodFailed, comment: models::PublicComment, user: Option<models::UserSessionInfo>, reason: String, code: String) -> CreateCommentPublic200Response {
        CreateCommentPublic200Response {
            status,
            comment: Box::new(comment),
            user: if let Some(x) = user {Some(Box::new(x))} else {None},
            module_data: None,
            user_id_ws: None,
            reason,
            code,
            secondary_code: None,
            banned_until: None,
            max_character_length: None,
            translated_error: None,
            custom_config: None,
        }
    }
}

