/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiUserSubscriptionData {
    #[serde(rename = "pageTitle", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "anonUserId", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl CreateApiUserSubscriptionData {
    pub fn new(url_id: String) -> CreateApiUserSubscriptionData {
        CreateApiUserSubscriptionData {
            page_title: None,
            url: None,
            url_id,
            anon_user_id: None,
            user_id: None,
        }
    }
}

