/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiPageData {
    #[serde(rename = "accessibleByGroupIds", skip_serializing_if = "Option::is_none")]
    pub accessible_by_group_ids: Option<Vec<String>>,
    #[serde(rename = "rootCommentCount", skip_serializing_if = "Option::is_none")]
    pub root_comment_count: Option<i64>,
    #[serde(rename = "commentCount", skip_serializing_if = "Option::is_none")]
    pub comment_count: Option<i64>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
}

impl CreateApiPageData {
    pub fn new(title: String, url: String, url_id: String) -> CreateApiPageData {
        CreateApiPageData {
            accessible_by_group_ids: None,
            root_comment_count: None,
            comment_count: None,
            title,
            url,
            url_id,
        }
    }
}

