/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateModeratorBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "moderationGroupIds", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Vec<String>>,
}

impl CreateModeratorBody {
    pub fn new(name: String, email: String) -> CreateModeratorBody {
        CreateModeratorBody {
            name,
            email,
            user_id: None,
            moderation_group_ids: None,
        }
    }
}

