/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomConfigParameters {
    #[serde(rename = "absoluteAndRelativeDates", skip_serializing_if = "Option::is_none")]
    pub absolute_and_relative_dates: Option<bool>,
    #[serde(rename = "absoluteDates", skip_serializing_if = "Option::is_none")]
    pub absolute_dates: Option<bool>,
    #[serde(rename = "allowAnon", skip_serializing_if = "Option::is_none")]
    pub allow_anon: Option<bool>,
    #[serde(rename = "allowAnonFlag", skip_serializing_if = "Option::is_none")]
    pub allow_anon_flag: Option<bool>,
    #[serde(rename = "allowAnonVotes", skip_serializing_if = "Option::is_none")]
    pub allow_anon_votes: Option<bool>,
    #[serde(rename = "allowedLanguages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_languages: Option<Option<Vec<String>>>,
    #[serde(rename = "collapseReplies", skip_serializing_if = "Option::is_none")]
    pub collapse_replies: Option<bool>,
    #[serde(rename = "commentCountFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment_count_format: Option<Option<String>>,
    #[serde(rename = "commentHTMLRenderingMode", skip_serializing_if = "Option::is_none")]
    pub comment_html_rendering_mode: Option<models::CommentHtmlRenderingMode>,
    #[serde(rename = "commentThreadDeleteMode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment_thread_delete_mode: Option<Option<models::CommentThreadDeletionMode>>,
    #[serde(rename = "commenterNameFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_name_format: Option<Option<models::CommenterNameFormats>>,
    #[serde(rename = "countAboveToggle", skip_serializing_if = "Option::is_none")]
    pub count_above_toggle: Option<i32>,
    #[serde(rename = "customCSS", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_css: Option<Option<String>>,
    #[serde(rename = "defaultAvatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_avatar_src: Option<Option<String>>,
    #[serde(rename = "defaultSortDirection", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_sort_direction: Option<Option<models::SortDirections>>,
    #[serde(rename = "defaultUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_username: Option<Option<String>>,
    #[serde(rename = "disableAutoAdminMigration", skip_serializing_if = "Option::is_none")]
    pub disable_auto_admin_migration: Option<bool>,
    #[serde(rename = "disableAutoHashTagCreation", skip_serializing_if = "Option::is_none")]
    pub disable_auto_hash_tag_creation: Option<bool>,
    #[serde(rename = "disableBlocking", skip_serializing_if = "Option::is_none")]
    pub disable_blocking: Option<bool>,
    #[serde(rename = "disableCommenterCommentDelete", skip_serializing_if = "Option::is_none")]
    pub disable_commenter_comment_delete: Option<bool>,
    #[serde(rename = "disableCommenterCommentEdit", skip_serializing_if = "Option::is_none")]
    pub disable_commenter_comment_edit: Option<bool>,
    #[serde(rename = "disableEmailInputs", skip_serializing_if = "Option::is_none")]
    pub disable_email_inputs: Option<bool>,
    #[serde(rename = "disableLiveCommenting", skip_serializing_if = "Option::is_none")]
    pub disable_live_commenting: Option<bool>,
    #[serde(rename = "disableNotificationBell", skip_serializing_if = "Option::is_none")]
    pub disable_notification_bell: Option<bool>,
    #[serde(rename = "disableProfiles", skip_serializing_if = "Option::is_none")]
    pub disable_profiles: Option<bool>,
    #[serde(rename = "disableSuccessMessage", skip_serializing_if = "Option::is_none")]
    pub disable_success_message: Option<bool>,
    #[serde(rename = "disableToolbar", skip_serializing_if = "Option::is_none")]
    pub disable_toolbar: Option<bool>,
    #[serde(rename = "disableUnverifiedLabel", skip_serializing_if = "Option::is_none")]
    pub disable_unverified_label: Option<bool>,
    #[serde(rename = "disableVoting", skip_serializing_if = "Option::is_none")]
    pub disable_voting: Option<bool>,
    #[serde(rename = "enableCommenterLinks", skip_serializing_if = "Option::is_none")]
    pub enable_commenter_links: Option<bool>,
    #[serde(rename = "enableSearch", skip_serializing_if = "Option::is_none")]
    pub enable_search: Option<bool>,
    #[serde(rename = "enableSpoilers", skip_serializing_if = "Option::is_none")]
    pub enable_spoilers: Option<bool>,
    #[serde(rename = "enableThirdPartyCookieBypass", skip_serializing_if = "Option::is_none")]
    pub enable_third_party_cookie_bypass: Option<bool>,
    #[serde(rename = "enableViewCounts", skip_serializing_if = "Option::is_none")]
    pub enable_view_counts: Option<bool>,
    #[serde(rename = "enableVoteList", skip_serializing_if = "Option::is_none")]
    pub enable_vote_list: Option<bool>,
    #[serde(rename = "enableWYSIWYG", skip_serializing_if = "Option::is_none")]
    pub enable_wysiwyg: Option<bool>,
    #[serde(rename = "gifRating", skip_serializing_if = "Option::is_none")]
    pub gif_rating: Option<models::GifRating>,
    #[serde(rename = "hasDarkBackground", skip_serializing_if = "Option::is_none")]
    pub has_dark_background: Option<bool>,
    #[serde(rename = "headerHTML", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub header_html: Option<Option<String>>,
    #[serde(rename = "hideAvatars", skip_serializing_if = "Option::is_none")]
    pub hide_avatars: Option<bool>,
    #[serde(rename = "hideCommentsUnderCountTextFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hide_comments_under_count_text_format: Option<Option<String>>,
    #[serde(rename = "imageContentProfanityLevel", skip_serializing_if = "Option::is_none")]
    pub image_content_profanity_level: Option<models::ImageContentProfanityLevel>,
    #[serde(rename = "inputAfterComments", skip_serializing_if = "Option::is_none")]
    pub input_after_comments: Option<bool>,
    #[serde(rename = "limitCommentsByGroups", skip_serializing_if = "Option::is_none")]
    pub limit_comments_by_groups: Option<bool>,
    #[serde(rename = "locale", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub locale: Option<Option<String>>,
    #[serde(rename = "maxCommentCharacterLength", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_comment_character_length: Option<Option<i32>>,
    #[serde(rename = "maxCommentCreatedCountPUPM", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_comment_created_count_pupm: Option<Option<i32>>,
    #[serde(rename = "noCustomConfig", skip_serializing_if = "Option::is_none")]
    pub no_custom_config: Option<bool>,
    #[serde(rename = "noImageUploads", skip_serializing_if = "Option::is_none")]
    pub no_image_uploads: Option<bool>,
    #[serde(rename = "noStyles", skip_serializing_if = "Option::is_none")]
    pub no_styles: Option<bool>,
    #[serde(rename = "pageSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Option<i32>>,
    #[serde(rename = "readonly", skip_serializing_if = "Option::is_none")]
    pub readonly: Option<bool>,
    #[serde(rename = "requireSSO", skip_serializing_if = "Option::is_none")]
    pub require_sso: Option<bool>,
    #[serde(rename = "enableResizeHandle", skip_serializing_if = "Option::is_none")]
    pub enable_resize_handle: Option<bool>,
    #[serde(rename = "restrictedLinkDomains", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub restricted_link_domains: Option<Option<Vec<String>>>,
    #[serde(rename = "showBadgesInTopBar", skip_serializing_if = "Option::is_none")]
    pub show_badges_in_top_bar: Option<bool>,
    #[serde(rename = "showCommentSaveSuccess", skip_serializing_if = "Option::is_none")]
    pub show_comment_save_success: Option<bool>,
    #[serde(rename = "showLiveRightAway", skip_serializing_if = "Option::is_none")]
    pub show_live_right_away: Option<bool>,
    #[serde(rename = "showQuestion", skip_serializing_if = "Option::is_none")]
    pub show_question: Option<bool>,
    #[serde(rename = "spamRules", skip_serializing_if = "Option::is_none")]
    pub spam_rules: Option<Vec<models::SpamRule>>,
    #[serde(rename = "ssoSecLvl", skip_serializing_if = "Option::is_none")]
    pub sso_sec_lvl: Option<models::SsoSecurityLevel>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub translations: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "useShowCommentsToggle", skip_serializing_if = "Option::is_none")]
    pub use_show_comments_toggle: Option<bool>,
    #[serde(rename = "useSingleLineCommentInput", skip_serializing_if = "Option::is_none")]
    pub use_single_line_comment_input: Option<bool>,
    #[serde(rename = "voteStyle", skip_serializing_if = "Option::is_none")]
    pub vote_style: Option<models::VoteStyle>,
    #[serde(rename = "widgetQuestionId", skip_serializing_if = "Option::is_none")]
    pub widget_question_id: Option<String>,
    #[serde(rename = "widgetQuestionResultsStyle", skip_serializing_if = "Option::is_none")]
    pub widget_question_results_style: Option<models::CommentQuestionResultsRenderingType>,
    #[serde(rename = "widgetQuestionStyle", skip_serializing_if = "Option::is_none")]
    pub widget_question_style: Option<models::QuestionRenderingType>,
    #[serde(rename = "widgetQuestionWhenToSave", skip_serializing_if = "Option::is_none")]
    pub widget_question_when_to_save: Option<models::QuestionWhenSave>,
    #[serde(rename = "widgetQuestionsRequired", skip_serializing_if = "Option::is_none")]
    pub widget_questions_required: Option<models::CommentQuestionsRequired>,
    #[serde(rename = "widgetSubQuestionVisibility", skip_serializing_if = "Option::is_none")]
    pub widget_sub_question_visibility: Option<models::QuestionSubQuestionVisibility>,
    #[serde(rename = "wrap", skip_serializing_if = "Option::is_none")]
    pub wrap: Option<bool>,
}

impl CustomConfigParameters {
    pub fn new() -> CustomConfigParameters {
        CustomConfigParameters {
            absolute_and_relative_dates: None,
            absolute_dates: None,
            allow_anon: None,
            allow_anon_flag: None,
            allow_anon_votes: None,
            allowed_languages: None,
            collapse_replies: None,
            comment_count_format: None,
            comment_html_rendering_mode: None,
            comment_thread_delete_mode: None,
            commenter_name_format: None,
            count_above_toggle: None,
            custom_css: None,
            default_avatar_src: None,
            default_sort_direction: None,
            default_username: None,
            disable_auto_admin_migration: None,
            disable_auto_hash_tag_creation: None,
            disable_blocking: None,
            disable_commenter_comment_delete: None,
            disable_commenter_comment_edit: None,
            disable_email_inputs: None,
            disable_live_commenting: None,
            disable_notification_bell: None,
            disable_profiles: None,
            disable_success_message: None,
            disable_toolbar: None,
            disable_unverified_label: None,
            disable_voting: None,
            enable_commenter_links: None,
            enable_search: None,
            enable_spoilers: None,
            enable_third_party_cookie_bypass: None,
            enable_view_counts: None,
            enable_vote_list: None,
            enable_wysiwyg: None,
            gif_rating: None,
            has_dark_background: None,
            header_html: None,
            hide_avatars: None,
            hide_comments_under_count_text_format: None,
            image_content_profanity_level: None,
            input_after_comments: None,
            limit_comments_by_groups: None,
            locale: None,
            max_comment_character_length: None,
            max_comment_created_count_pupm: None,
            no_custom_config: None,
            no_image_uploads: None,
            no_styles: None,
            page_size: None,
            readonly: None,
            require_sso: None,
            enable_resize_handle: None,
            restricted_link_domains: None,
            show_badges_in_top_bar: None,
            show_comment_save_success: None,
            show_live_right_away: None,
            show_question: None,
            spam_rules: None,
            sso_sec_lvl: None,
            translations: None,
            use_show_comments_toggle: None,
            use_single_line_comment_input: None,
            vote_style: None,
            widget_question_id: None,
            widget_question_results_style: None,
            widget_question_style: None,
            widget_question_when_to_save: None,
            widget_questions_required: None,
            widget_sub_question_visibility: None,
            wrap: None,
        }
    }
}

