/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteFeedPostPublic200ResponseAnyOf {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl DeleteFeedPostPublic200ResponseAnyOf {
    pub fn new(status: models::ApiStatus) -> DeleteFeedPostPublic200ResponseAnyOf {
        DeleteFeedPostPublic200ResponseAnyOf {
            status,
        }
    }
}

