/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplateRenderErrorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "customTemplateId")]
    pub custom_template_id: String,
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "count")]
    pub count: f64,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "lastOccurredAt")]
    pub last_occurred_at: chrono::DateTime<chrono::FixedOffset>,
}

impl EmailTemplateRenderErrorResponse {
    pub fn new(id: String, tenant_id: String, custom_template_id: String, error: String, count: f64, created_at: chrono::DateTime<chrono::FixedOffset>, last_occurred_at: chrono::DateTime<chrono::FixedOffset>) -> EmailTemplateRenderErrorResponse {
        EmailTemplateRenderErrorResponse {
            id,
            tenant_id,
            custom_template_id,
            error,
            count,
            created_at,
            last_occurred_at,
        }
    }
}

