/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventLogEntry {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "broadcastId")]
    pub broadcast_id: String,
    #[serde(rename = "data")]
    pub data: String,
}

impl EventLogEntry {
    pub fn new(_id: String, created_at: String, tenant_id: String, url_id: String, broadcast_id: String, data: String) -> EventLogEntry {
        EventLogEntry {
            _id,
            created_at,
            tenant_id,
            url_id,
            broadcast_id,
            data,
        }
    }
}

