/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FComment {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "urlIdRaw", skip_serializing_if = "Option::is_none")]
    pub url_id_raw: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pageTitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "anonUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<Option<String>>,
    #[serde(rename = "commenterEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<Option<String>>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "date", deserialize_with = "Option::deserialize")]
    pub date: Option<String>,
    #[serde(rename = "localDateString", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<Option<String>>,
    #[serde(rename = "localDateHours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_hours: Option<Option<i32>>,
    #[serde(rename = "votes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Option<i32>>,
    #[serde(rename = "votesUp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<Option<i32>>,
    #[serde(rename = "votesDown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<Option<i32>>,
    #[serde(rename = "expireAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<Option<String>>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "verifiedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verified_date: Option<Option<String>>,
    #[serde(rename = "verificationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_id: Option<Option<String>>,
    #[serde(rename = "notificationSentForParent", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent: Option<bool>,
    #[serde(rename = "notificationSentForParentTenant", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent_tenant: Option<bool>,
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "imported", skip_serializing_if = "Option::is_none")]
    pub imported: Option<bool>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "externalParentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_parent_id: Option<Option<String>>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "aiDeterminedSpam", skip_serializing_if = "Option::is_none")]
    pub ai_determined_spam: Option<bool>,
    #[serde(rename = "hasImages", skip_serializing_if = "Option::is_none")]
    pub has_images: Option<bool>,
    #[serde(rename = "pageNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<Option<i32>>,
    #[serde(rename = "pageNumberOF", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_number_of: Option<Option<i32>>,
    #[serde(rename = "pageNumberNF", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_number_nf: Option<Option<i32>>,
    #[serde(rename = "hasLinks", skip_serializing_if = "Option::is_none")]
    pub has_links: Option<bool>,
    #[serde(rename = "hasCode", skip_serializing_if = "Option::is_none")]
    pub has_code: Option<bool>,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<String>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isBannedUser", skip_serializing_if = "Option::is_none")]
    pub is_banned_user: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<Option<bool>>,
    #[serde(rename = "isLocked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<Option<bool>>,
    #[serde(rename = "flagCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_count: Option<Option<i32>>,
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<f64>>,
    #[serde(rename = "displayLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<Option<String>>,
    #[serde(rename = "fromProductId", skip_serializing_if = "Option::is_none")]
    pub from_product_id: Option<i32>,
    #[serde(rename = "meta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Option<models::FCommentMeta>>,
    #[serde(rename = "ipHash", skip_serializing_if = "Option::is_none")]
    pub ip_hash: Option<String>,
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<models::CommentUserMentionInfo>>,
    #[serde(rename = "hashTags", skip_serializing_if = "Option::is_none")]
    pub hash_tags: Option<Vec<models::CommentUserHashTagInfo>>,
    #[serde(rename = "badges", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Option<Vec<models::CommentUserBadgeInfo>>>,
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "veteranBadgeProcessed", skip_serializing_if = "Option::is_none")]
    pub veteran_badge_processed: Option<String>,
    #[serde(rename = "moderationGroupIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "didProcessBadges", skip_serializing_if = "Option::is_none")]
    pub did_process_badges: Option<bool>,
    #[serde(rename = "fromOfflineRestore", skip_serializing_if = "Option::is_none")]
    pub from_offline_restore: Option<bool>,
    #[serde(rename = "autoplayJobId", skip_serializing_if = "Option::is_none")]
    pub autoplay_job_id: Option<String>,
    #[serde(rename = "autoplayDelayMS", skip_serializing_if = "Option::is_none")]
    pub autoplay_delay_ms: Option<i64>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    #[serde(rename = "logs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logs: Option<Option<Vec<Vec<serde_json::Value>>>>,
    #[serde(rename = "groupIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "viewCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub view_count: Option<Option<f64>>,
    #[serde(rename = "requiresVerification", skip_serializing_if = "Option::is_none")]
    pub requires_verification: Option<bool>,
    #[serde(rename = "editKey", skip_serializing_if = "Option::is_none")]
    pub edit_key: Option<String>,
}

impl FComment {
    pub fn new(_id: String, tenant_id: String, url_id: String, url: String, commenter_name: String, comment: String, comment_html: String, date: Option<String>, verified: bool, approved: bool, locale: Option<String>) -> FComment {
        FComment {
            _id,
            tenant_id,
            url_id,
            url_id_raw: None,
            url,
            page_title: None,
            user_id: None,
            anon_user_id: None,
            commenter_email: None,
            commenter_name,
            commenter_link: None,
            comment,
            comment_html,
            parent_id: None,
            date,
            local_date_string: None,
            local_date_hours: None,
            votes: None,
            votes_up: None,
            votes_down: None,
            expire_at: None,
            verified,
            verified_date: None,
            verification_id: None,
            notification_sent_for_parent: None,
            notification_sent_for_parent_tenant: None,
            reviewed: None,
            imported: None,
            external_id: None,
            external_parent_id: None,
            avatar_src: None,
            is_spam: None,
            ai_determined_spam: None,
            has_images: None,
            page_number: None,
            page_number_of: None,
            page_number_nf: None,
            has_links: None,
            has_code: None,
            approved,
            locale,
            is_deleted: None,
            is_deleted_user: None,
            is_banned_user: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            flag_count: None,
            rating: None,
            display_label: None,
            from_product_id: None,
            meta: None,
            ip_hash: None,
            mentions: None,
            hash_tags: None,
            badges: None,
            domain: None,
            veteran_badge_processed: None,
            moderation_group_ids: None,
            did_process_badges: None,
            from_offline_restore: None,
            autoplay_job_id: None,
            autoplay_delay_ms: None,
            feedback_ids: None,
            logs: None,
            group_ids: None,
            view_count: None,
            requires_verification: None,
            edit_key: None,
        }
    }
}

