/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedPostMediaItem {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "linkUrl", skip_serializing_if = "Option::is_none")]
    pub link_url: Option<String>,
    #[serde(rename = "sizes")]
    pub sizes: Vec<models::FeedPostMediaItemAsset>,
}

impl FeedPostMediaItem {
    pub fn new(sizes: Vec<models::FeedPostMediaItemAsset>) -> FeedPostMediaItem {
        FeedPostMediaItem {
            title: None,
            link_url: None,
            sizes,
        }
    }
}

