/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedPost {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "fromUserId", skip_serializing_if = "Option::is_none")]
    pub from_user_id: Option<String>,
    #[serde(rename = "fromUserDisplayName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_user_display_name: Option<Option<String>>,
    #[serde(rename = "fromUserAvatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_user_avatar: Option<Option<String>>,
    #[serde(rename = "fromIpHash", skip_serializing_if = "Option::is_none")]
    pub from_ip_hash: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "contentHTML", skip_serializing_if = "Option::is_none")]
    pub content_html: Option<String>,
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<Vec<models::FeedPostMediaItem>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::FeedPostLink>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "reacts", skip_serializing_if = "Option::is_none")]
    pub reacts: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "commentCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment_count: Option<Option<i32>>,
}

impl FeedPost {
    pub fn new(_id: String, tenant_id: String, created_at: String) -> FeedPost {
        FeedPost {
            _id,
            tenant_id,
            title: None,
            from_user_id: None,
            from_user_display_name: None,
            from_user_avatar: None,
            from_ip_hash: None,
            tags: None,
            weight: None,
            meta: None,
            content_html: None,
            media: None,
            links: None,
            created_at,
            reacts: None,
            comment_count: None,
        }
    }
}

