/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedPostMediaItem {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "sizes", skip_serializing_if = "Option::is_none")]
    pub sizes: Option<Box<models::FeedPostMediaItemAsset>>,
}

impl FeedPostMediaItem {
    pub fn new() -> FeedPostMediaItem {
        FeedPostMediaItem {
            title: None,
            link: None,
            sizes: None,
        }
    }
}

