/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEmailTemplateRenderErrorsResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "renderErrors")]
    pub render_errors: Vec<models::EmailTemplateRenderErrorResponse>,
}

impl GetEmailTemplateRenderErrorsResponse {
    pub fn new(status: models::ApiStatus, render_errors: Vec<models::EmailTemplateRenderErrorResponse>) -> GetEmailTemplateRenderErrorsResponse {
        GetEmailTemplateRenderErrorsResponse {
            status,
            render_errors,
        }
    }
}

