/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEmailTemplateResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "emailTemplate")]
    pub email_template: Box<models::CustomEmailTemplate>,
}

impl GetEmailTemplateResponse {
    pub fn new(status: models::ApiStatus, email_template: models::CustomEmailTemplate) -> GetEmailTemplateResponse {
        GetEmailTemplateResponse {
            status,
            email_template: Box::new(email_template),
        }
    }
}

