/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCachedNotificationCountResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "data")]
    pub data: Box<models::UserNotificationCount>,
}

impl GetCachedNotificationCountResponse {
    pub fn new(status: models::ApiStatus, data: models::UserNotificationCount) -> GetCachedNotificationCountResponse {
        GetCachedNotificationCountResponse {
            status,
            data: Box::new(data),
        }
    }
}

