/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetV2PageReacts {
    #[serde(rename = "reactedIds", skip_serializing_if = "Option::is_none")]
    pub reacted_ids: Option<Vec<String>>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "counts", skip_serializing_if = "Option::is_none")]
    pub counts: Option<std::collections::HashMap<String, f64>>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl GetV2PageReacts {
    pub fn new(status: models::ApiStatus) -> GetV2PageReacts {
        GetV2PageReacts {
            reacted_ids: None,
            counts: None,
            status,
        }
    }
}

