/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomainConfigsResponseAnyOf {
    #[serde(rename = "configurations", deserialize_with = "Option::deserialize")]
    pub configurations: Option<serde_json::Value>,
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<serde_json::Value>,
}

impl GetDomainConfigsResponseAnyOf {
    pub fn new(configurations: Option<serde_json::Value>, status: Option<serde_json::Value>) -> GetDomainConfigsResponseAnyOf {
        GetDomainConfigsResponseAnyOf {
            configurations,
            status,
        }
    }
}

