/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetV2PageReactUsersResponse {
    #[serde(rename = "userNames")]
    pub user_names: Vec<String>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl GetV2PageReactUsersResponse {
    pub fn new(user_names: Vec<String>, status: models::ApiStatus) -> GetV2PageReactUsersResponse {
        GetV2PageReactUsersResponse {
            user_names,
            status,
        }
    }
}

