/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomainConfigResponse {
    #[serde(rename = "configuration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Option<serde_json::Value>>,
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<serde_json::Value>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl GetDomainConfigResponse {
    pub fn new(status: Option<serde_json::Value>) -> GetDomainConfigResponse {
        GetDomainConfigResponse {
            configuration: None,
            status,
            reason: None,
            code: None,
        }
    }
}

