/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubscriptionsApiResponse {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::ApiUserSubscription>>,
    #[serde(rename = "status")]
    pub status: String,
}

impl GetSubscriptionsApiResponse {
    pub fn new(status: String) -> GetSubscriptionsApiResponse {
        GetSubscriptionsApiResponse {
            reason: None,
            code: None,
            subscriptions: None,
            status,
        }
    }
}

