/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVotesResponse1 {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "appliedAuthorizedVotes", skip_serializing_if = "Option::is_none")]
    pub applied_authorized_votes: Option<Vec<models::PublicVote>>,
    #[serde(rename = "appliedAnonymousVotes", skip_serializing_if = "Option::is_none")]
    pub applied_anonymous_votes: Option<Vec<models::PublicVote>>,
    #[serde(rename = "pendingVotes", skip_serializing_if = "Option::is_none")]
    pub pending_votes: Option<Vec<models::PublicVote>>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "secondaryCode", skip_serializing_if = "Option::is_none")]
    pub secondary_code: Option<String>,
    #[serde(rename = "bannedUntil", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<i64>,
    #[serde(rename = "maxCharacterLength", skip_serializing_if = "Option::is_none")]
    pub max_character_length: Option<i32>,
    #[serde(rename = "translatedError", skip_serializing_if = "Option::is_none")]
    pub translated_error: Option<String>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
}

impl GetVotesResponse1 {
    pub fn new(status: models::ApiStatus) -> GetVotesResponse1 {
        GetVotesResponse1 {
            status,
            applied_authorized_votes: None,
            applied_anonymous_votes: None,
            pending_votes: None,
            reason: None,
            code: None,
            secondary_code: None,
            banned_until: None,
            max_character_length: None,
            translated_error: None,
            custom_config: None,
        }
    }
}

