/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUserInternalProfileResponseProfile {
    #[serde(rename = "commenterName", skip_serializing_if = "Option::is_none")]
    pub commenter_name: Option<String>,
    #[serde(rename = "firstCommentDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_comment_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "ipHash", skip_serializing_if = "Option::is_none")]
    pub ip_hash: Option<String>,
    #[serde(rename = "countryFlag", skip_serializing_if = "Option::is_none")]
    pub country_flag: Option<String>,
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "websiteUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<Option<String>>,
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(rename = "karma", skip_serializing_if = "Option::is_none")]
    pub karma: Option<f64>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "commenterEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "anonUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
}

impl GetUserInternalProfileResponseProfile {
    pub fn new() -> GetUserInternalProfileResponseProfile {
        GetUserInternalProfileResponseProfile {
            commenter_name: None,
            first_comment_date: None,
            ip_hash: None,
            country_flag: None,
            country_code: None,
            website_url: None,
            bio: None,
            karma: None,
            locale: None,
            verified: None,
            avatar_src: None,
            display_name: None,
            username: None,
            commenter_email: None,
            email: None,
            anon_user_id: None,
            user_id: None,
        }
    }
}

