/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPendingWebhookEventsResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "pendingWebhookEvents")]
    pub pending_webhook_events: Vec<models::PendingCommentToSyncOutbound>,
}

impl GetPendingWebhookEventsResponse {
    pub fn new(status: models::ApiStatus, pending_webhook_events: Vec<models::PendingCommentToSyncOutbound>) -> GetPendingWebhookEventsResponse {
        GetPendingWebhookEventsResponse {
            status,
            pending_webhook_events,
        }
    }
}

