/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCommentBanStatusResponse {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "emailDomain", deserialize_with = "Option::deserialize")]
    pub email_domain: Option<String>,
    #[serde(rename = "canIPBan", deserialize_with = "Option::deserialize")]
    pub can_ip_ban: Option<bool>,
}

impl GetCommentBanStatusResponse {
    pub fn new(status: String, email_domain: Option<String>, can_ip_ban: Option<bool>) -> GetCommentBanStatusResponse {
        GetCommentBanStatusResponse {
            status,
            email_domain,
            can_ip_ban,
        }
    }
}

