/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetQuestionConfigsResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "questionConfigs")]
    pub question_configs: Vec<models::QuestionConfig>,
}

impl GetQuestionConfigsResponse {
    pub fn new(status: models::ApiStatus, question_configs: Vec<models::QuestionConfig>) -> GetQuestionConfigsResponse {
        GetQuestionConfigsResponse {
            status,
            question_configs,
        }
    }
}

