/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetV1PageLikes {
    #[serde(rename = "urlIdWS")]
    pub url_id_ws: String,
    #[serde(rename = "didLike")]
    pub did_like: bool,
    #[serde(rename = "commentCount")]
    pub comment_count: i32,
    #[serde(rename = "likeCount")]
    pub like_count: i32,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl GetV1PageLikes {
    pub fn new(url_id_ws: String, did_like: bool, comment_count: i32, like_count: i32, status: models::ApiStatus) -> GetV1PageLikes {
        GetV1PageLikes {
            url_id_ws,
            did_like,
            comment_count,
            like_count,
            status,
        }
    }
}

