/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBannedUsersCountResponse {
    #[serde(rename = "totalCount")]
    pub total_count: f64,
    #[serde(rename = "status")]
    pub status: String,
}

impl GetBannedUsersCountResponse {
    pub fn new(total_count: f64, status: String) -> GetBannedUsersCountResponse {
        GetBannedUsersCountResponse {
            total_count,
            status,
        }
    }
}

