/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCommentsResponsePublicComment {
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "comments")]
    pub comments: Vec<models::PublicComment>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<Box<models::UserSessionInfo>>,
    #[serde(rename = "urlIdClean", skip_serializing_if = "Option::is_none")]
    pub url_id_clean: Option<String>,
    #[serde(rename = "lastGenDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_gen_date: Option<Option<i64>>,
    #[serde(rename = "includesPastPages", skip_serializing_if = "Option::is_none")]
    pub includes_past_pages: Option<bool>,
    #[serde(rename = "isDemo", skip_serializing_if = "Option::is_none")]
    pub is_demo: Option<bool>,
    #[serde(rename = "commentCount", skip_serializing_if = "Option::is_none")]
    pub comment_count: Option<i32>,
    #[serde(rename = "isSiteAdmin", skip_serializing_if = "Option::is_none")]
    pub is_site_admin: Option<bool>,
    #[serde(rename = "hasBillingIssue", skip_serializing_if = "Option::is_none")]
    pub has_billing_issue: Option<bool>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "moduleData", skip_serializing_if = "Option::is_none")]
    pub module_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "pageNumber")]
    pub page_number: i32,
    #[serde(rename = "isWhiteLabeled", skip_serializing_if = "Option::is_none")]
    pub is_white_labeled: Option<bool>,
    #[serde(rename = "isProd", skip_serializing_if = "Option::is_none")]
    pub is_prod: Option<bool>,
    #[serde(rename = "isCrawler", skip_serializing_if = "Option::is_none")]
    pub is_crawler: Option<bool>,
    #[serde(rename = "notificationCount", skip_serializing_if = "Option::is_none")]
    pub notification_count: Option<i32>,
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "isClosed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    #[serde(rename = "presencePollState", skip_serializing_if = "Option::is_none")]
    pub presence_poll_state: Option<i32>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
}

impl GetCommentsResponsePublicComment {
    pub fn new(status: String, comments: Vec<models::PublicComment>, user: Option<models::UserSessionInfo>, page_number: i32) -> GetCommentsResponsePublicComment {
        GetCommentsResponsePublicComment {
            status_code: None,
            status,
            code: None,
            reason: None,
            comments,
            user: if let Some(x) = user {Some(Box::new(x))} else {None},
            url_id_clean: None,
            last_gen_date: None,
            includes_past_pages: None,
            is_demo: None,
            comment_count: None,
            is_site_admin: None,
            has_billing_issue: None,
            module_data: None,
            page_number,
            is_white_labeled: None,
            is_prod: None,
            is_crawler: None,
            notification_count: None,
            has_more: None,
            is_closed: None,
            presence_poll_state: None,
            custom_config: None,
        }
    }
}

