/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSsoUsersResponse {
    #[serde(rename = "users")]
    pub users: Vec<models::ApissoUser>,
    #[serde(rename = "status")]
    pub status: String,
}

impl GetSsoUsersResponse {
    pub fn new(users: Vec<models::ApissoUser>, status: String) -> GetSsoUsersResponse {
        GetSsoUsersResponse {
            users,
            status,
        }
    }
}

