/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUserNotificationCountResponse {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "count")]
    pub count: i64,
}

impl GetUserNotificationCountResponse {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess, count: i64) -> GetUserNotificationCountResponse {
        GetUserNotificationCountResponse {
            status,
            count,
        }
    }
}

