/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveEvent {
    #[serde(rename = "type")]
    pub r#type: models::LiveEventType,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<i64>,
    #[serde(rename = "broadcastId", skip_serializing_if = "Option::is_none")]
    pub broadcast_id: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "badges", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Vec<models::CommentUserBadgeInfo>>,
    #[serde(rename = "notification", skip_serializing_if = "Option::is_none")]
    pub notification: Option<Box<models::UserNotification>>,
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Box<models::PubSubVote>>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Box<models::PubSubComment>>,
    #[serde(rename = "feedPost", skip_serializing_if = "Option::is_none")]
    pub feed_post: Option<Box<models::FeedPost>>,
    #[serde(rename = "extraInfo", skip_serializing_if = "Option::is_none")]
    pub extra_info: Option<Box<models::LiveEventExtraInfo>>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "isClosed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    #[serde(rename = "uj", skip_serializing_if = "Option::is_none")]
    pub uj: Option<Vec<String>>,
    #[serde(rename = "ul", skip_serializing_if = "Option::is_none")]
    pub ul: Option<Vec<String>>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<std::collections::HashMap<String, i32>>,
}

impl LiveEvent {
    pub fn new(r#type: models::LiveEventType) -> LiveEvent {
        LiveEvent {
            r#type,
            timestamp: None,
            ts: None,
            broadcast_id: None,
            user_id: None,
            badges: None,
            notification: None,
            vote: None,
            comment: None,
            feed_post: None,
            extra_info: None,
            config: None,
            is_closed: None,
            uj: None,
            ul: None,
            changes: None,
        }
    }
}

