/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LiveEventType {
    #[serde(rename = "update-badges")]
    UpdateBadges,
    #[serde(rename = "notification")]
    Notification,
    #[serde(rename = "p-u")]
    PU,
    #[serde(rename = "new-vote")]
    NewVote,
    #[serde(rename = "deleted-vote")]
    DeletedVote,
    #[serde(rename = "new-comment")]
    NewComment,
    #[serde(rename = "updated-comment")]
    UpdatedComment,
    #[serde(rename = "deleted-comment")]
    DeletedComment,
    #[serde(rename = "cvc")]
    Cvc,
    #[serde(rename = "new-config")]
    NewConfig,
    #[serde(rename = "thread-state-change")]
    ThreadStateChange,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "dfr")]
    Dfr,
    #[serde(rename = "new-feed-post")]
    NewFeedPost,
    #[serde(rename = "updated-feed-post")]
    UpdatedFeedPost,
    #[serde(rename = "deleted-feed-post")]
    DeletedFeedPost,

}

impl std::fmt::Display for LiveEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UpdateBadges => write!(f, "update-badges"),
            Self::Notification => write!(f, "notification"),
            Self::PU => write!(f, "p-u"),
            Self::NewVote => write!(f, "new-vote"),
            Self::DeletedVote => write!(f, "deleted-vote"),
            Self::NewComment => write!(f, "new-comment"),
            Self::UpdatedComment => write!(f, "updated-comment"),
            Self::DeletedComment => write!(f, "deleted-comment"),
            Self::Cvc => write!(f, "cvc"),
            Self::NewConfig => write!(f, "new-config"),
            Self::ThreadStateChange => write!(f, "thread-state-change"),
            Self::Fr => write!(f, "fr"),
            Self::Dfr => write!(f, "dfr"),
            Self::NewFeedPost => write!(f, "new-feed-post"),
            Self::UpdatedFeedPost => write!(f, "updated-feed-post"),
            Self::DeletedFeedPost => write!(f, "deleted-feed-post"),
        }
    }
}

impl Default for LiveEventType {
    fn default() -> LiveEventType {
        Self::UpdateBadges
    }
}

