/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaAsset {
    #[serde(rename = "w")]
    pub w: i32,
    #[serde(rename = "h")]
    pub h: i32,
    #[serde(rename = "src")]
    pub src: String,
}

impl MediaAsset {
    pub fn new(w: i32, h: i32, src: String) -> MediaAsset {
        MediaAsset {
            w,
            h,
            src,
        }
    }
}

