/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationApiCommentResponse {
    #[serde(rename = "comment")]
    pub comment: Box<models::ModerationApiComment>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl ModerationApiCommentResponse {
    pub fn new(comment: models::ModerationApiComment, status: models::ApiStatus) -> ModerationApiCommentResponse {
        ModerationApiCommentResponse {
            comment: Box::new(comment),
            status,
        }
    }
}

