/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationApiGetLogsResponse {
    #[serde(rename = "logs")]
    pub logs: Vec<models::ModerationApiCommentLog>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl ModerationApiGetLogsResponse {
    pub fn new(logs: Vec<models::ModerationApiCommentLog>, status: models::ApiStatus) -> ModerationApiGetLogsResponse {
        ModerationApiGetLogsResponse {
            logs,
            status,
        }
    }
}

