/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationUserSearchResponse {
    #[serde(rename = "users")]
    pub users: Vec<models::ModerationUserSearchProjected>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl ModerationUserSearchResponse {
    pub fn new(users: Vec<models::ModerationUserSearchProjected>, status: models::ApiStatus) -> ModerationUserSearchResponse {
        ModerationUserSearchResponse {
            users,
            status,
        }
    }
}

