/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationApiComment {
    #[serde(rename = "isLocalDeleted", skip_serializing_if = "Option::is_none")]
    pub is_local_deleted: Option<bool>,
    #[serde(rename = "replyCount", skip_serializing_if = "Option::is_none")]
    pub reply_count: Option<f64>,
    #[serde(rename = "feedbackResults", skip_serializing_if = "Option::is_none")]
    pub feedback_results: Option<Vec<String>>,
    #[serde(rename = "isVotedUp", skip_serializing_if = "Option::is_none")]
    pub is_voted_up: Option<bool>,
    #[serde(rename = "isVotedDown", skip_serializing_if = "Option::is_none")]
    pub is_voted_down: Option<bool>,
    #[serde(rename = "myVoteId", skip_serializing_if = "Option::is_none")]
    pub my_vote_id: Option<String>,
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pageTitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "anonUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<Option<String>>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "date", deserialize_with = "Option::deserialize")]
    pub date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "localDateString", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<Option<String>>,
    #[serde(rename = "votes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Option<f64>>,
    #[serde(rename = "votesUp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<Option<f64>>,
    #[serde(rename = "votesDown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<Option<f64>>,
    #[serde(rename = "expireAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "permNotSpam", skip_serializing_if = "Option::is_none")]
    pub perm_not_spam: Option<bool>,
    #[serde(rename = "hasLinks", skip_serializing_if = "Option::is_none")]
    pub has_links: Option<bool>,
    #[serde(rename = "hasCode", skip_serializing_if = "Option::is_none")]
    pub has_code: Option<bool>,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<String>,
    #[serde(rename = "isBannedUser", skip_serializing_if = "Option::is_none")]
    pub is_banned_user: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<Option<bool>>,
    #[serde(rename = "isLocked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<Option<bool>>,
    #[serde(rename = "flagCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_count: Option<Option<f64>>,
    #[serde(rename = "displayLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<Option<String>>,
    #[serde(rename = "badges", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Option<Vec<models::CommentUserBadgeInfo>>>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
}

impl ModerationApiComment {
    pub fn new(_id: String, tenant_id: String, url_id: String, url: String, commenter_name: String, comment_html: String, date: Option<chrono::DateTime<chrono::FixedOffset>>, approved: bool, locale: Option<String>, verified: bool) -> ModerationApiComment {
        ModerationApiComment {
            is_local_deleted: None,
            reply_count: None,
            feedback_results: None,
            is_voted_up: None,
            is_voted_down: None,
            my_vote_id: None,
            _id,
            tenant_id,
            url_id,
            url,
            page_title: None,
            user_id: None,
            anon_user_id: None,
            commenter_name,
            commenter_link: None,
            comment_html,
            parent_id: None,
            date,
            local_date_string: None,
            votes: None,
            votes_up: None,
            votes_down: None,
            expire_at: None,
            reviewed: None,
            avatar_src: None,
            is_spam: None,
            perm_not_spam: None,
            has_links: None,
            has_code: None,
            approved,
            locale,
            is_banned_user: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            flag_count: None,
            display_label: None,
            badges: None,
            verified,
            feedback_ids: None,
            is_deleted: None,
        }
    }
}

