/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationFilter {
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "isBannedUser", skip_serializing_if = "Option::is_none")]
    pub is_banned_user: Option<bool>,
    #[serde(rename = "isLocked", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<bool>,
    #[serde(rename = "flagCountGt", skip_serializing_if = "Option::is_none")]
    pub flag_count_gt: Option<f64>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "urlId", skip_serializing_if = "Option::is_none")]
    pub url_id: Option<String>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "moderationGroupIds", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Vec<String>>,
    /// Text search terms. Each term is matched case-insensitively against the comment text. A term wrapped in quotes means exact phrase match.
    #[serde(rename = "commentTextSearch", skip_serializing_if = "Option::is_none")]
    pub comment_text_search: Option<Vec<String>>,
    /// Set by the `exact=\"...\"` search syntax. The comment text must equal this value exactly (case-sensitive, full-string), as opposed to the substring matching of commentTextSearch.
    #[serde(rename = "exactCommentText", skip_serializing_if = "Option::is_none")]
    pub exact_comment_text: Option<String>,
}

impl ModerationFilter {
    pub fn new() -> ModerationFilter {
        ModerationFilter {
            reviewed: None,
            approved: None,
            is_spam: None,
            is_banned_user: None,
            is_locked: None,
            flag_count_gt: None,
            user_id: None,
            url_id: None,
            domain: None,
            moderation_group_ids: None,
            comment_text_search: None,
            exact_comment_text: None,
        }
    }
}

