/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationUserSearchProjected {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "displayName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<Option<String>>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
}

impl ModerationUserSearchProjected {
    pub fn new(_id: String, username: String) -> ModerationUserSearchProjected {
        ModerationUserSearchProjected {
            _id,
            username,
            display_name: None,
            avatar_src: None,
        }
    }
}

