/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageUsersOnlineResponse {
    #[serde(rename = "nextAfterUserId", deserialize_with = "Option::deserialize")]
    pub next_after_user_id: Option<String>,
    #[serde(rename = "nextAfterName", deserialize_with = "Option::deserialize")]
    pub next_after_name: Option<String>,
    #[serde(rename = "totalCount")]
    pub total_count: f64,
    #[serde(rename = "anonCount")]
    pub anon_count: f64,
    #[serde(rename = "users")]
    pub users: Vec<models::PageUserEntry>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl PageUsersOnlineResponse {
    pub fn new(next_after_user_id: Option<String>, next_after_name: Option<String>, total_count: f64, anon_count: f64, users: Vec<models::PageUserEntry>, status: models::ApiStatus) -> PageUsersOnlineResponse {
        PageUsersOnlineResponse {
            next_after_user_id,
            next_after_name,
            total_count,
            anon_count,
            users,
            status,
        }
    }
}

