/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchDomainConfigParams {
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "emailFromName", skip_serializing_if = "Option::is_none")]
    pub email_from_name: Option<String>,
    #[serde(rename = "emailFromEmail", skip_serializing_if = "Option::is_none")]
    pub email_from_email: Option<String>,
    #[serde(rename = "logoSrc", skip_serializing_if = "Option::is_none")]
    pub logo_src: Option<String>,
    #[serde(rename = "logoSrc100px", skip_serializing_if = "Option::is_none")]
    pub logo_src100px: Option<String>,
    #[serde(rename = "footerUnsubscribeURL", skip_serializing_if = "Option::is_none")]
    pub footer_unsubscribe_url: Option<String>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "emailHeaders", skip_serializing_if = "Option::is_none")]
    pub email_headers: Option<std::collections::HashMap<String, String>>,
}

impl PatchDomainConfigParams {
    pub fn new() -> PatchDomainConfigParams {
        PatchDomainConfigParams {
            domain: None,
            email_from_name: None,
            email_from_email: None,
            logo_src: None,
            logo_src100px: None,
            footer_unsubscribe_url: None,
            email_headers: None,
        }
    }
}

