/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchSsoUserApiResponse {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::ApissoUser>>,
    #[serde(rename = "status")]
    pub status: String,
}

impl PatchSsoUserApiResponse {
    pub fn new(status: String) -> PatchSsoUserApiResponse {
        PatchSsoUserApiResponse {
            reason: None,
            code: None,
            user: None,
            status,
        }
    }
}

