/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId {
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
}

impl PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(commenter_name: String, comment_html: String) -> PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId {
        PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId {
            user_id: None,
            commenter_name,
            comment_html,
            is_deleted: None,
        }
    }
}

