/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PickTenantAuditLogPeriodTenantAuditLogKeys : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickTenantAuditLogPeriodTenantAuditLogKeys {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "resourceName")]
    pub resource_name: String,
    #[serde(rename = "crudType")]
    pub crud_type: CrudType,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<From>,
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(rename = "when", skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "serverStartDate", skip_serializing_if = "Option::is_none")]
    pub server_start_date: Option<String>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "objectDetails", skip_serializing_if = "Option::is_none")]
    pub object_details: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PickTenantAuditLogPeriodTenantAuditLogKeys {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(_id: String, resource_name: String, crud_type: CrudType) -> PickTenantAuditLogPeriodTenantAuditLogKeys {
        PickTenantAuditLogPeriodTenantAuditLogKeys {
            _id,
            url: None,
            user_id: None,
            username: None,
            resource_name,
            crud_type,
            from: None,
            ip: None,
            when: None,
            description: None,
            server_start_date: None,
            object_details: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CrudType {
    #[serde(rename = "c")]
    C,
    #[serde(rename = "r")]
    R,
    #[serde(rename = "u")]
    U,
    #[serde(rename = "d")]
    D,
    #[serde(rename = "login")]
    Login,
}

impl Default for CrudType {
    fn default() -> CrudType {
        Self::C
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum From {
    #[serde(rename = "ui")]
    Ui,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "cron")]
    Cron,
}

impl Default for From {
    fn default() -> From {
        Self::Ui
    }
}

