/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PickUserNotificationPeriodIdOrUrlIdOrUrlOrPageTitleOrRelatedObjectTypeOrRelatedObjectIdOrViewedOrSentOrCreatedAtOrTypeOrFromCommentIdOrFromUserNameOrFromUserIdOrFromUserAvatarSrcOrOptedOut : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickUserNotificationPeriodIdOrUrlIdOrUrlOrPageTitleOrRelatedObjectTypeOrRelatedObjectIdOrViewedOrSentOrCreatedAtOrTypeOrFromCommentIdOrFromUserNameOrFromUserIdOrFromUserAvatarSrcOrOptedOut {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pageTitle", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<String>,
    #[serde(rename = "relatedObjectType")]
    pub related_object_type: f64,
    #[serde(rename = "relatedObjectId")]
    pub related_object_id: String,
    #[serde(rename = "viewed")]
    pub viewed: bool,
    #[serde(rename = "sent")]
    pub sent: bool,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "type")]
    pub r#type: models::NotificationType,
    #[serde(rename = "fromCommentId", skip_serializing_if = "Option::is_none")]
    pub from_comment_id: Option<String>,
    #[serde(rename = "fromUserName")]
    pub from_user_name: String,
    #[serde(rename = "fromUserId")]
    pub from_user_id: String,
    #[serde(rename = "fromUserAvatarSrc", skip_serializing_if = "Option::is_none")]
    pub from_user_avatar_src: Option<String>,
    #[serde(rename = "optedOut")]
    pub opted_out: bool,
}

impl PickUserNotificationPeriodIdOrUrlIdOrUrlOrPageTitleOrRelatedObjectTypeOrRelatedObjectIdOrViewedOrSentOrCreatedAtOrTypeOrFromCommentIdOrFromUserNameOrFromUserIdOrFromUserAvatarSrcOrOptedOut {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(_id: String, url_id: String, url: String, related_object_type: f64, related_object_id: String, viewed: bool, sent: bool, created_at: String, r#type: models::NotificationType, from_user_name: String, from_user_id: String, opted_out: bool) -> PickUserNotificationPeriodIdOrUrlIdOrUrlOrPageTitleOrRelatedObjectTypeOrRelatedObjectIdOrViewedOrSentOrCreatedAtOrTypeOrFromCommentIdOrFromUserNameOrFromUserIdOrFromUserAvatarSrcOrOptedOut {
        PickUserNotificationPeriodIdOrUrlIdOrUrlOrPageTitleOrRelatedObjectTypeOrRelatedObjectIdOrViewedOrSentOrCreatedAtOrTypeOrFromCommentIdOrFromUserNameOrFromUserIdOrFromUserAvatarSrcOrOptedOut {
            _id,
            url_id,
            url,
            page_title: None,
            related_object_type,
            related_object_id,
            viewed,
            sent,
            created_at,
            r#type,
            from_comment_id: None,
            from_user_name,
            from_user_id,
            from_user_avatar_src: None,
            opted_out,
        }
    }
}

