/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// PickFCommentPeriodApprovedOrCommentHtml : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickFCommentPeriodApprovedOrCommentHtml {
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "approved")]
    pub approved: bool,
}

impl PickFCommentPeriodApprovedOrCommentHtml {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(comment_html: String, approved: bool) -> PickFCommentPeriodApprovedOrCommentHtml {
        PickFCommentPeriodApprovedOrCommentHtml {
            comment_html,
            approved,
        }
    }
}

