/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// PickApiCommentPeriodUpdatableCommentFields : From T, pick a set of properties whose keys are in the union K
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PickApiCommentPeriodUpdatableCommentFields {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "urlIdRaw", skip_serializing_if = "Option::is_none")]
    pub url_id_raw: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pageTitle", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "commenterEmail", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<String>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterLink", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<String>,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "localDateString", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<String>,
    #[serde(rename = "localDateHours", skip_serializing_if = "Option::is_none")]
    pub local_date_hours: Option<i32>,
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<i32>,
    #[serde(rename = "votesUp", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<i32>,
    #[serde(rename = "votesDown", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<i32>,
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<String>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "verifiedDate", skip_serializing_if = "Option::is_none")]
    pub verified_date: Option<String>,
    #[serde(rename = "notificationSentForParent", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent: Option<bool>,
    #[serde(rename = "notificationSentForParentTenant", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent_tenant: Option<bool>,
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "externalParentId", skip_serializing_if = "Option::is_none")]
    pub external_parent_id: Option<String>,
    #[serde(rename = "avatarSrc", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<String>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<bool>,
    #[serde(rename = "isLocked", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<bool>,
    #[serde(rename = "flagCount", skip_serializing_if = "Option::is_none")]
    pub flag_count: Option<i32>,
    #[serde(rename = "displayLabel", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<String>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<models::PickFCommentApiCommentFieldsKeysMeta>,
    #[serde(rename = "moderationGroupIds", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Vec<String>>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
}

impl PickApiCommentPeriodUpdatableCommentFields {
    /// From T, pick a set of properties whose keys are in the union K
    pub fn new(date: String, url_id: String, url: String, commenter_name: String, comment: String, comment_html: String, verified: bool, approved: bool) -> PickApiCommentPeriodUpdatableCommentFields {
        PickApiCommentPeriodUpdatableCommentFields {
            date,
            url_id,
            url_id_raw: None,
            url,
            page_title: None,
            user_id: None,
            commenter_email: None,
            commenter_name,
            commenter_link: None,
            comment,
            comment_html,
            parent_id: None,
            local_date_string: None,
            local_date_hours: None,
            votes: None,
            votes_up: None,
            votes_down: None,
            expire_at: None,
            verified,
            verified_date: None,
            notification_sent_for_parent: None,
            notification_sent_for_parent_tenant: None,
            reviewed: None,
            external_id: None,
            external_parent_id: None,
            avatar_src: None,
            is_spam: None,
            approved,
            is_deleted: None,
            is_deleted_user: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            flag_count: None,
            display_label: None,
            meta: None,
            moderation_group_ids: None,
            feedback_ids: None,
        }
    }
}

