/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostRemoveCommentApiResponse {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl PostRemoveCommentApiResponse {
    pub fn new(action: String, status: String) -> PostRemoveCommentApiResponse {
        PostRemoveCommentApiResponse {
            action,
            status,
        }
    }
}

