/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreBanSummary {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "usernames")]
    pub usernames: Vec<String>,
    #[serde(rename = "count")]
    pub count: f64,
}

impl PreBanSummary {
    pub fn new(status: models::ApiStatus, usernames: Vec<String>, count: f64) -> PreBanSummary {
        PreBanSummary {
            status,
            usernames,
            count,
        }
    }
}

