/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PubSubVote {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "urlIdRaw")]
    pub url_id_raw: String,
    #[serde(rename = "commentId")]
    pub comment_id: String,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "direction")]
    pub direction: i32,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    #[serde(rename = "verificationId", deserialize_with = "Option::deserialize")]
    pub verification_id: Option<String>,
}

impl PubSubVote {
    pub fn new(_id: String, tenant_id: String, url_id: String, url_id_raw: String, comment_id: String, direction: i32, created_at: i64, verification_id: Option<String>) -> PubSubVote {
        PubSubVote {
            _id,
            tenant_id,
            url_id,
            url_id_raw,
            comment_id,
            user_id: None,
            direction,
            created_at,
            verification_id,
        }
    }
}

