/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicVote {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
    #[serde(rename = "commentId")]
    pub comment_id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "direction")]
    pub direction: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PublicVote {
    pub fn new(id: String, url_id: String, comment_id: String, user_id: String, direction: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> PublicVote {
        PublicVote {
            id,
            url_id,
            comment_id,
            user_id,
            direction,
            created_at,
        }
    }
}

