/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiSetCommentTextResponse {
    #[serde(rename = "comment")]
    pub comment: Box<models::PickFCommentPeriodApprovedOrCommentHtml>,
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
}

impl PublicApiSetCommentTextResponse {
    pub fn new(comment: models::PickFCommentPeriodApprovedOrCommentHtml, status: models::ImportedApiStatusPeriodSuccess) -> PublicApiSetCommentTextResponse {
        PublicApiSetCommentTextResponse {
            comment: Box::new(comment),
            status,
        }
    }
}

