/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiDeleteCommentResponse {
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Box<models::PickFCommentPeriodIsDeletedOrCommentHtmlOrCommenterNameOrUserId>>,
    #[serde(rename = "hardRemoved")]
    pub hard_removed: bool,
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
}

impl PublicApiDeleteCommentResponse {
    pub fn new(hard_removed: bool, status: models::ImportedApiStatusPeriodSuccess) -> PublicApiDeleteCommentResponse {
        PublicApiDeleteCommentResponse {
            comment: None,
            hard_removed,
            status,
        }
    }
}

