/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicCommentBase {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "commenterName")]
    pub commenter_name: String,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "commentHTML")]
    pub comment_html: String,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "date", deserialize_with = "Option::deserialize")]
    pub date: Option<String>,
    #[serde(rename = "votes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Option<i32>>,
    #[serde(rename = "votesUp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<Option<i32>>,
    #[serde(rename = "votesDown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<Option<i32>>,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "hasImages", skip_serializing_if = "Option::is_none")]
    pub has_images: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<Option<bool>>,
    #[serde(rename = "isLocked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<Option<bool>>,
    #[serde(rename = "displayLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<Option<String>>,
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<f64>>,
    #[serde(rename = "badges", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Option<Vec<models::CommentUserBadgeInfo>>>,
    #[serde(rename = "viewCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub view_count: Option<Option<i64>>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "anonUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub anon_user_id: Option<Option<String>>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
    #[serde(rename = "requiresVerification", skip_serializing_if = "Option::is_none")]
    pub requires_verification: Option<bool>,
    #[serde(rename = "editKey", skip_serializing_if = "Option::is_none")]
    pub edit_key: Option<String>,
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
}

impl PublicCommentBase {
    pub fn new(_id: String, commenter_name: String, comment_html: String, date: Option<String>, verified: bool) -> PublicCommentBase {
        PublicCommentBase {
            _id,
            user_id: None,
            commenter_name,
            commenter_link: None,
            comment_html,
            parent_id: None,
            date,
            votes: None,
            votes_up: None,
            votes_down: None,
            verified,
            avatar_src: None,
            has_images: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            display_label: None,
            rating: None,
            badges: None,
            view_count: None,
            is_deleted: None,
            is_deleted_user: None,
            is_spam: None,
            anon_user_id: None,
            feedback_ids: None,
            requires_verification: None,
            edit_key: None,
            approved: None,
        }
    }
}

