/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicApiGetCommentTextResponse {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "commentText")]
    pub comment_text: String,
    #[serde(rename = "sanitizedCommentText")]
    pub sanitized_comment_text: String,
}

impl PublicApiGetCommentTextResponse {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess, comment_text: String, sanitized_comment_text: String) -> PublicApiGetCommentTextResponse {
        PublicApiGetCommentTextResponse {
            status,
            comment_text,
            sanitized_comment_text,
        }
    }
}

