/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicPage {
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    #[serde(rename = "commentCount")]
    pub comment_count: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "urlId")]
    pub url_id: String,
}

impl PublicPage {
    pub fn new(updated_at: i64, comment_count: i32, title: String, url: String, url_id: String) -> PublicPage {
        PublicPage {
            updated_at,
            comment_count,
            title,
            url,
            url_id,
        }
    }
}

