/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuestionSubQuestionVisibility {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,

}

impl std::fmt::Display for QuestionSubQuestionVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant0 => write!(f, "0"),
            Self::Variant1 => write!(f, "1"),
        }
    }
}

impl Default for QuestionSubQuestionVisibility {
    fn default() -> QuestionSubQuestionVisibility {
        Self::Variant0
    }
}

