/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionDatum {
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "v")]
    pub v: std::collections::HashMap<String, f64>,
    #[serde(rename = "total")]
    pub total: f64,
}

impl QuestionDatum {
    pub fn new(v: std::collections::HashMap<String, f64>, total: f64) -> QuestionDatum {
        QuestionDatum {
            v,
            total,
        }
    }
}

