/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionConfigCustomOptionsInner {
    #[serde(rename = "imageSrc")]
    pub image_src: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl QuestionConfigCustomOptionsInner {
    pub fn new(image_src: String, name: String) -> QuestionConfigCustomOptionsInner {
        QuestionConfigCustomOptionsInner {
            image_src,
            name,
        }
    }
}

