/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReactBodyParams {
    #[serde(rename = "reactType", skip_serializing_if = "Option::is_none")]
    pub react_type: Option<String>,
}

impl ReactBodyParams {
    pub fn new() -> ReactBodyParams {
        ReactBodyParams {
            react_type: None,
        }
    }
}

