/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordStringBeforeStringOrNullAfterStringOrNullValue {
    #[serde(rename = "after", deserialize_with = "Option::deserialize")]
    pub after: Option<String>,
    #[serde(rename = "before", deserialize_with = "Option::deserialize")]
    pub before: Option<String>,
}

impl RecordStringBeforeStringOrNullAfterStringOrNullValue {
    pub fn new(after: Option<String>, before: Option<String>) -> RecordStringBeforeStringOrNullAfterStringOrNullValue {
        RecordStringBeforeStringOrNullAfterStringOrNullValue {
            after,
            before,
        }
    }
}

