/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderEmailTemplateResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "html")]
    pub html: String,
}

impl RenderEmailTemplateResponse {
    pub fn new(status: models::ApiStatus, html: String) -> RenderEmailTemplateResponse {
        RenderEmailTemplateResponse {
            status,
            html,
        }
    }
}

