/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetUserNotificationsResponse {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<Code>,
}

impl ResetUserNotificationsResponse {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess) -> ResetUserNotificationsResponse {
        ResetUserNotificationsResponse {
            status,
            code: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "ignored-since-impersonated")]
    IgnoredSinceImpersonated,
}

impl Default for Code {
    fn default() -> Code {
        Self::IgnoredSinceImpersonated
    }
}

