/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaveCommentResponse {
    #[serde(rename = "status")]
    pub status: models::ImportedApiStatusPeriodSuccess,
    #[serde(rename = "comment")]
    pub comment: Box<models::FComment>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<Box<models::UserSessionInfo>>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "moduleData", skip_serializing_if = "Option::is_none")]
    pub module_data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl SaveCommentResponse {
    pub fn new(status: models::ImportedApiStatusPeriodSuccess, comment: models::FComment, user: Option<models::UserSessionInfo>) -> SaveCommentResponse {
        SaveCommentResponse {
            status,
            comment: Box::new(comment),
            user: if let Some(x) = user {Some(Box::new(x))} else {None},
            module_data: None,
        }
    }
}

