/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchUsersSectionedResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "sections")]
    pub sections: Vec<models::UserSearchSectionResult>,
}

impl SearchUsersSectionedResponse {
    pub fn new(status: models::ApiStatus, sections: Vec<models::UserSearchSectionResult>) -> SearchUsersSectionedResponse {
        SearchUsersSectionedResponse {
            status,
            sections,
        }
    }
}

