/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetCommentApprovedResponse {
    #[serde(rename = "didResetFlaggedCount", skip_serializing_if = "Option::is_none")]
    pub did_reset_flagged_count: Option<bool>,
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
}

impl SetCommentApprovedResponse {
    pub fn new(status: models::ApiStatus) -> SetCommentApprovedResponse {
        SetCommentApprovedResponse {
            did_reset_flagged_count: None,
            status,
        }
    }
}

