/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SizePreset {
    #[serde(rename = "Default")]
    Default,
    #[serde(rename = "CrossPlatform")]
    CrossPlatform,

}

impl std::fmt::Display for SizePreset {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Default => write!(f, "Default"),
            Self::CrossPlatform => write!(f, "CrossPlatform"),
        }
    }
}

impl Default for SizePreset {
    fn default() -> SizePreset {
        Self::Default
    }
}

