/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortDirections {
    #[serde(rename = "OF")]
    Of,
    #[serde(rename = "NF")]
    Nf,
    #[serde(rename = "MR")]
    Mr,

}

impl std::fmt::Display for SortDirections {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Of => write!(f, "OF"),
            Self::Nf => write!(f, "NF"),
            Self::Mr => write!(f, "MR"),
        }
    }
}

impl Default for SortDirections {
    fn default() -> SortDirections {
        Self::Of
    }
}

