/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantPackage {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
    #[serde(rename = "monthlyCostUSD", deserialize_with = "Option::deserialize")]
    pub monthly_cost_usd: Option<f64>,
    #[serde(rename = "yearlyCostUSD", deserialize_with = "Option::deserialize")]
    pub yearly_cost_usd: Option<f64>,
    #[serde(rename = "monthlyStripePlanId", deserialize_with = "Option::deserialize")]
    pub monthly_stripe_plan_id: Option<String>,
    #[serde(rename = "yearlyStripePlanId", deserialize_with = "Option::deserialize")]
    pub yearly_stripe_plan_id: Option<String>,
    #[serde(rename = "maxMonthlyPageLoads")]
    pub max_monthly_page_loads: f64,
    #[serde(rename = "maxMonthlyAPICredits")]
    pub max_monthly_api_credits: f64,
    #[serde(rename = "maxMonthlySmallWidgetsCredits")]
    pub max_monthly_small_widgets_credits: f64,
    #[serde(rename = "maxMonthlyComments")]
    pub max_monthly_comments: f64,
    #[serde(rename = "maxConcurrentUsers")]
    pub max_concurrent_users: f64,
    #[serde(rename = "maxTenantUsers")]
    pub max_tenant_users: f64,
    #[serde(rename = "maxSSOUsers")]
    pub max_sso_users: f64,
    #[serde(rename = "maxModerators")]
    pub max_moderators: f64,
    #[serde(rename = "maxDomains")]
    pub max_domains: f64,
    #[serde(rename = "maxWhiteLabeledTenants")]
    pub max_white_labeled_tenants: f64,
    #[serde(rename = "maxMonthlyEventLogRequests")]
    pub max_monthly_event_log_requests: f64,
    #[serde(rename = "maxCustomCollectionSize")]
    pub max_custom_collection_size: f64,
    #[serde(rename = "hasWhiteLabeling")]
    pub has_white_labeling: bool,
    #[serde(rename = "hasDebranding")]
    pub has_debranding: bool,
    #[serde(rename = "hasLLMSpamDetection")]
    pub has_llm_spam_detection: bool,
    #[serde(rename = "forWhoText")]
    pub for_who_text: String,
    #[serde(rename = "featureTaglines")]
    pub feature_taglines: Vec<String>,
    #[serde(rename = "hasAuditing")]
    pub has_auditing: bool,
    #[serde(rename = "hasFlexPricing")]
    pub has_flex_pricing: bool,
    #[serde(rename = "enableSAML", skip_serializing_if = "Option::is_none")]
    pub enable_saml: Option<bool>,
    #[serde(rename = "enableCanvasLTI", skip_serializing_if = "Option::is_none")]
    pub enable_canvas_lti: Option<bool>,
    #[serde(rename = "flexPageLoadCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_page_load_cost_cents: Option<f64>,
    #[serde(rename = "flexPageLoadUnit", skip_serializing_if = "Option::is_none")]
    pub flex_page_load_unit: Option<f64>,
    #[serde(rename = "flexCommentCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_comment_cost_cents: Option<f64>,
    #[serde(rename = "flexCommentUnit", skip_serializing_if = "Option::is_none")]
    pub flex_comment_unit: Option<f64>,
    #[serde(rename = "flexSSOUserCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_sso_user_cost_cents: Option<f64>,
    #[serde(rename = "flexSSOUserUnit", skip_serializing_if = "Option::is_none")]
    pub flex_sso_user_unit: Option<f64>,
    #[serde(rename = "flexAPICreditCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_api_credit_cost_cents: Option<f64>,
    #[serde(rename = "flexAPICreditUnit", skip_serializing_if = "Option::is_none")]
    pub flex_api_credit_unit: Option<f64>,
    #[serde(rename = "flexSmallWidgetsCreditCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_small_widgets_credit_cost_cents: Option<f64>,
    #[serde(rename = "flexSmallWidgetsCreditUnit", skip_serializing_if = "Option::is_none")]
    pub flex_small_widgets_credit_unit: Option<f64>,
    #[serde(rename = "flexModeratorCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_moderator_cost_cents: Option<f64>,
    #[serde(rename = "flexModeratorUnit", skip_serializing_if = "Option::is_none")]
    pub flex_moderator_unit: Option<f64>,
    #[serde(rename = "flexAdminCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_admin_cost_cents: Option<f64>,
    #[serde(rename = "flexAdminUnit", skip_serializing_if = "Option::is_none")]
    pub flex_admin_unit: Option<f64>,
    #[serde(rename = "flexDomainCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_domain_cost_cents: Option<f64>,
    #[serde(rename = "flexDomainUnit", skip_serializing_if = "Option::is_none")]
    pub flex_domain_unit: Option<f64>,
    #[serde(rename = "flexChatGPTCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_chat_gpt_cost_cents: Option<f64>,
    #[serde(rename = "flexChatGPTUnit", skip_serializing_if = "Option::is_none")]
    pub flex_chat_gpt_unit: Option<f64>,
    #[serde(rename = "flexLLMCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_llm_cost_cents: Option<f64>,
    #[serde(rename = "flexLLMUnit", skip_serializing_if = "Option::is_none")]
    pub flex_llm_unit: Option<f64>,
    #[serde(rename = "flexMinimumCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_minimum_cost_cents: Option<f64>,
    #[serde(rename = "flexManagedTenantCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_managed_tenant_cost_cents: Option<f64>,
    #[serde(rename = "flexSSOAdminCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_sso_admin_cost_cents: Option<f64>,
    #[serde(rename = "flexSSOAdminUnit", skip_serializing_if = "Option::is_none")]
    pub flex_sso_admin_unit: Option<f64>,
    #[serde(rename = "flexSSOModeratorCostCents", skip_serializing_if = "Option::is_none")]
    pub flex_sso_moderator_cost_cents: Option<f64>,
    #[serde(rename = "flexSSOModeratorUnit", skip_serializing_if = "Option::is_none")]
    pub flex_sso_moderator_unit: Option<f64>,
    #[serde(rename = "isSSOBillingMonthlyActiveUsers", skip_serializing_if = "Option::is_none")]
    pub is_sso_billing_monthly_active_users: Option<bool>,
    #[serde(rename = "hasAIAgents", skip_serializing_if = "Option::is_none")]
    pub has_ai_agents: Option<bool>,
    #[serde(rename = "maxAIAgents", skip_serializing_if = "Option::is_none")]
    pub max_ai_agents: Option<f64>,
    #[serde(rename = "aiAgentDailyBudgetCents", skip_serializing_if = "Option::is_none")]
    pub ai_agent_daily_budget_cents: Option<f64>,
    #[serde(rename = "aiAgentMonthlyBudgetCents", skip_serializing_if = "Option::is_none")]
    pub ai_agent_monthly_budget_cents: Option<f64>,
}

impl TenantPackage {
    pub fn new(_id: String, name: String, tenant_id: String, created_at: chrono::DateTime<chrono::FixedOffset>, monthly_cost_usd: Option<f64>, yearly_cost_usd: Option<f64>, monthly_stripe_plan_id: Option<String>, yearly_stripe_plan_id: Option<String>, max_monthly_page_loads: f64, max_monthly_api_credits: f64, max_monthly_small_widgets_credits: f64, max_monthly_comments: f64, max_concurrent_users: f64, max_tenant_users: f64, max_sso_users: f64, max_moderators: f64, max_domains: f64, max_white_labeled_tenants: f64, max_monthly_event_log_requests: f64, max_custom_collection_size: f64, has_white_labeling: bool, has_debranding: bool, has_llm_spam_detection: bool, for_who_text: String, feature_taglines: Vec<String>, has_auditing: bool, has_flex_pricing: bool) -> TenantPackage {
        TenantPackage {
            _id,
            name,
            tenant_id,
            created_at,
            template_id: None,
            monthly_cost_usd,
            yearly_cost_usd,
            monthly_stripe_plan_id,
            yearly_stripe_plan_id,
            max_monthly_page_loads,
            max_monthly_api_credits,
            max_monthly_small_widgets_credits,
            max_monthly_comments,
            max_concurrent_users,
            max_tenant_users,
            max_sso_users,
            max_moderators,
            max_domains,
            max_white_labeled_tenants,
            max_monthly_event_log_requests,
            max_custom_collection_size,
            has_white_labeling,
            has_debranding,
            has_llm_spam_detection,
            for_who_text,
            feature_taglines,
            has_auditing,
            has_flex_pricing,
            enable_saml: None,
            enable_canvas_lti: None,
            flex_page_load_cost_cents: None,
            flex_page_load_unit: None,
            flex_comment_cost_cents: None,
            flex_comment_unit: None,
            flex_sso_user_cost_cents: None,
            flex_sso_user_unit: None,
            flex_api_credit_cost_cents: None,
            flex_api_credit_unit: None,
            flex_small_widgets_credit_cost_cents: None,
            flex_small_widgets_credit_unit: None,
            flex_moderator_cost_cents: None,
            flex_moderator_unit: None,
            flex_admin_cost_cents: None,
            flex_admin_unit: None,
            flex_domain_cost_cents: None,
            flex_domain_unit: None,
            flex_chat_gpt_cost_cents: None,
            flex_chat_gpt_unit: None,
            flex_llm_cost_cents: None,
            flex_llm_unit: None,
            flex_minimum_cost_cents: None,
            flex_managed_tenant_cost_cents: None,
            flex_sso_admin_cost_cents: None,
            flex_sso_admin_unit: None,
            flex_sso_moderator_cost_cents: None,
            flex_sso_moderator_unit: None,
            is_sso_billing_monthly_active_users: None,
            has_ai_agents: None,
            max_ai_agents: None,
            ai_agent_daily_budget_cents: None,
            ai_agent_monthly_budget_cents: None,
        }
    }
}

