/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TosConfig {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "textByLocale", skip_serializing_if = "Option::is_none")]
    pub text_by_locale: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl TosConfig {
    pub fn new() -> TosConfig {
        TosConfig {
            enabled: None,
            text_by_locale: None,
            last_updated: None,
        }
    }
}

