/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApiPageData {
    #[serde(rename = "isClosed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    #[serde(rename = "accessibleByGroupIds", skip_serializing_if = "Option::is_none")]
    pub accessible_by_group_ids: Option<Vec<String>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "urlId", skip_serializing_if = "Option::is_none")]
    pub url_id: Option<String>,
}

impl UpdateApiPageData {
    pub fn new() -> UpdateApiPageData {
        UpdateApiPageData {
            is_closed: None,
            accessible_by_group_ids: None,
            title: None,
            url: None,
            url_id: None,
        }
    }
}

