/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTenantBody {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "signUpDate", skip_serializing_if = "Option::is_none")]
    pub sign_up_date: Option<f64>,
    #[serde(rename = "packageId", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<String>,
    #[serde(rename = "paymentFrequency", skip_serializing_if = "Option::is_none")]
    pub payment_frequency: Option<f64>,
    #[serde(rename = "billingInfoValid", skip_serializing_if = "Option::is_none")]
    pub billing_info_valid: Option<bool>,
    #[serde(rename = "billingHandledExternally", skip_serializing_if = "Option::is_none")]
    pub billing_handled_externally: Option<bool>,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    #[serde(rename = "isSetup", skip_serializing_if = "Option::is_none")]
    pub is_setup: Option<bool>,
    #[serde(rename = "domainConfiguration", skip_serializing_if = "Option::is_none")]
    pub domain_configuration: Option<Vec<models::ApiDomainConfiguration>>,
    #[serde(rename = "billingInfo", skip_serializing_if = "Option::is_none")]
    pub billing_info: Option<Box<models::BillingInfo>>,
    #[serde(rename = "stripeCustomerId", skip_serializing_if = "Option::is_none")]
    pub stripe_customer_id: Option<String>,
    #[serde(rename = "stripeSubscriptionId", skip_serializing_if = "Option::is_none")]
    pub stripe_subscription_id: Option<String>,
    #[serde(rename = "stripePlanId", skip_serializing_if = "Option::is_none")]
    pub stripe_plan_id: Option<String>,
    #[serde(rename = "enableProfanityFilter", skip_serializing_if = "Option::is_none")]
    pub enable_profanity_filter: Option<bool>,
    #[serde(rename = "enableSpamFilter", skip_serializing_if = "Option::is_none")]
    pub enable_spam_filter: Option<bool>,
    #[serde(rename = "removeUnverifiedComments", skip_serializing_if = "Option::is_none")]
    pub remove_unverified_comments: Option<bool>,
    #[serde(rename = "unverifiedCommentsTTLms", skip_serializing_if = "Option::is_none")]
    pub unverified_comments_tt_lms: Option<f64>,
    #[serde(rename = "commentsRequireApproval", skip_serializing_if = "Option::is_none")]
    pub comments_require_approval: Option<bool>,
    #[serde(rename = "autoApproveCommentOnVerification", skip_serializing_if = "Option::is_none")]
    pub auto_approve_comment_on_verification: Option<bool>,
    #[serde(rename = "sendProfaneToSpam", skip_serializing_if = "Option::is_none")]
    pub send_profane_to_spam: Option<bool>,
    #[serde(rename = "deAnonIpAddr", skip_serializing_if = "Option::is_none")]
    pub de_anon_ip_addr: Option<f64>,
    /// Construct a type with a set of properties K of type T
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "managedByTenantId", skip_serializing_if = "Option::is_none")]
    pub managed_by_tenant_id: Option<String>,
}

impl UpdateTenantBody {
    pub fn new() -> UpdateTenantBody {
        UpdateTenantBody {
            name: None,
            email: None,
            sign_up_date: None,
            package_id: None,
            payment_frequency: None,
            billing_info_valid: None,
            billing_handled_externally: None,
            created_by: None,
            is_setup: None,
            domain_configuration: None,
            billing_info: None,
            stripe_customer_id: None,
            stripe_subscription_id: None,
            stripe_plan_id: None,
            enable_profanity_filter: None,
            enable_spam_filter: None,
            remove_unverified_comments: None,
            unverified_comments_tt_lms: None,
            comments_require_approval: None,
            auto_approve_comment_on_verification: None,
            send_profane_to_spam: None,
            de_anon_ip_addr: None,
            meta: None,
            managed_by_tenant_id: None,
        }
    }
}

