/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApissoUserData {
    #[serde(rename = "groupIds", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Vec<String>>,
    #[serde(rename = "hasBlockedUsers", skip_serializing_if = "Option::is_none")]
    pub has_blocked_users: Option<bool>,
    #[serde(rename = "isProfileDMDisabled", skip_serializing_if = "Option::is_none")]
    pub is_profile_dm_disabled: Option<bool>,
    #[serde(rename = "isProfileCommentsPrivate", skip_serializing_if = "Option::is_none")]
    pub is_profile_comments_private: Option<bool>,
    #[serde(rename = "isProfileActivityPrivate", skip_serializing_if = "Option::is_none")]
    pub is_profile_activity_private: Option<bool>,
    #[serde(rename = "isCommentModeratorAdmin", skip_serializing_if = "Option::is_none")]
    pub is_comment_moderator_admin: Option<bool>,
    #[serde(rename = "isAdminAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin_admin: Option<bool>,
    #[serde(rename = "isAccountOwner", skip_serializing_if = "Option::is_none")]
    pub is_account_owner: Option<bool>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "displayLabel", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<String>,
    #[serde(rename = "optedInSubscriptionNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_subscription_notifications: Option<bool>,
    #[serde(rename = "optedInNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_notifications: Option<bool>,
    #[serde(rename = "avatarSrc", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<String>,
    #[serde(rename = "loginCount", skip_serializing_if = "Option::is_none")]
    pub login_count: Option<i32>,
    #[serde(rename = "createdFromUrlId", skip_serializing_if = "Option::is_none")]
    pub created_from_url_id: Option<String>,
    #[serde(rename = "signUpDate", skip_serializing_if = "Option::is_none")]
    pub sign_up_date: Option<i64>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "websiteUrl", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl UpdateApissoUserData {
    pub fn new() -> UpdateApissoUserData {
        UpdateApissoUserData {
            group_ids: None,
            has_blocked_users: None,
            is_profile_dm_disabled: None,
            is_profile_comments_private: None,
            is_profile_activity_private: None,
            is_comment_moderator_admin: None,
            is_admin_admin: None,
            is_account_owner: None,
            display_name: None,
            display_label: None,
            opted_in_subscription_notifications: None,
            opted_in_notifications: None,
            avatar_src: None,
            login_count: None,
            created_from_url_id: None,
            sign_up_date: None,
            email: None,
            website_url: None,
            username: None,
            id: None,
        }
    }
}

