/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateNotificationBody {
    #[serde(rename = "viewed", skip_serializing_if = "Option::is_none")]
    pub viewed: Option<bool>,
    #[serde(rename = "optedOut", skip_serializing_if = "Option::is_none")]
    pub opted_out: Option<bool>,
}

impl UpdateNotificationBody {
    pub fn new() -> UpdateNotificationBody {
        UpdateNotificationBody {
            viewed: None,
            opted_out: None,
        }
    }
}

