/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserBadgeParams {
    #[serde(rename = "displayedOnComments", skip_serializing_if = "Option::is_none")]
    pub displayed_on_comments: Option<bool>,
}

impl UpdateUserBadgeParams {
    pub fn new() -> UpdateUserBadgeParams {
        UpdateUserBadgeParams {
            displayed_on_comments: None,
        }
    }
}

