/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTenantUserBody {
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "websiteUrl", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "signUpDate", skip_serializing_if = "Option::is_none")]
    pub sign_up_date: Option<f64>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "loginCount", skip_serializing_if = "Option::is_none")]
    pub login_count: Option<f64>,
    #[serde(rename = "optedInNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_notifications: Option<bool>,
    #[serde(rename = "optedInTenantNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_tenant_notifications: Option<bool>,
    #[serde(rename = "hideAccountCode", skip_serializing_if = "Option::is_none")]
    pub hide_account_code: Option<bool>,
    #[serde(rename = "avatarSrc", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<String>,
    #[serde(rename = "isHelpRequestAdmin", skip_serializing_if = "Option::is_none")]
    pub is_help_request_admin: Option<bool>,
    #[serde(rename = "isAccountOwner", skip_serializing_if = "Option::is_none")]
    pub is_account_owner: Option<bool>,
    #[serde(rename = "isAdminAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin_admin: Option<bool>,
    #[serde(rename = "isBillingAdmin", skip_serializing_if = "Option::is_none")]
    pub is_billing_admin: Option<bool>,
    #[serde(rename = "isAnalyticsAdmin", skip_serializing_if = "Option::is_none")]
    pub is_analytics_admin: Option<bool>,
    #[serde(rename = "isCustomizationAdmin", skip_serializing_if = "Option::is_none")]
    pub is_customization_admin: Option<bool>,
    #[serde(rename = "isManageDataAdmin", skip_serializing_if = "Option::is_none")]
    pub is_manage_data_admin: Option<bool>,
    #[serde(rename = "isCommentModeratorAdmin", skip_serializing_if = "Option::is_none")]
    pub is_comment_moderator_admin: Option<bool>,
    #[serde(rename = "isAPIAdmin", skip_serializing_if = "Option::is_none")]
    pub is_api_admin: Option<bool>,
    #[serde(rename = "moderatorIds", skip_serializing_if = "Option::is_none")]
    pub moderator_ids: Option<Vec<String>>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "digestEmailFrequency", skip_serializing_if = "Option::is_none")]
    pub digest_email_frequency: Option<f64>,
    #[serde(rename = "displayLabel", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<String>,
}

impl UpdateTenantUserBody {
    pub fn new() -> UpdateTenantUserBody {
        UpdateTenantUserBody {
            username: None,
            display_name: None,
            website_url: None,
            email: None,
            sign_up_date: None,
            verified: None,
            login_count: None,
            opted_in_notifications: None,
            opted_in_tenant_notifications: None,
            hide_account_code: None,
            avatar_src: None,
            is_help_request_admin: None,
            is_account_owner: None,
            is_admin_admin: None,
            is_billing_admin: None,
            is_analytics_admin: None,
            is_customization_admin: None,
            is_manage_data_admin: None,
            is_comment_moderator_admin: None,
            is_api_admin: None,
            moderator_ids: None,
            locale: None,
            digest_email_frequency: None,
            display_label: None,
        }
    }
}

