/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatableCommentParams {
    #[serde(rename = "urlId", skip_serializing_if = "Option::is_none")]
    pub url_id: Option<String>,
    #[serde(rename = "urlIdRaw", skip_serializing_if = "Option::is_none")]
    pub url_id_raw: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "pageTitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "commenterEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_email: Option<Option<String>>,
    #[serde(rename = "commenterName", skip_serializing_if = "Option::is_none")]
    pub commenter_name: Option<String>,
    #[serde(rename = "commenterLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commenter_link: Option<Option<String>>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "commentHTML", skip_serializing_if = "Option::is_none")]
    pub comment_html: Option<String>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<f64>>,
    #[serde(rename = "localDateString", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_string: Option<Option<String>>,
    #[serde(rename = "localDateHours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_date_hours: Option<Option<i32>>,
    #[serde(rename = "votes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Option<i32>>,
    #[serde(rename = "votesUp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_up: Option<Option<i32>>,
    #[serde(rename = "votesDown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub votes_down: Option<Option<i32>>,
    #[serde(rename = "expireAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "verifiedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verified_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "notificationSentForParent", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent: Option<bool>,
    #[serde(rename = "notificationSentForParentTenant", skip_serializing_if = "Option::is_none")]
    pub notification_sent_for_parent_tenant: Option<bool>,
    #[serde(rename = "reviewed", skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "externalParentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_parent_id: Option<Option<String>>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "isSpam", skip_serializing_if = "Option::is_none")]
    pub is_spam: Option<bool>,
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    #[serde(rename = "isDeleted", skip_serializing_if = "Option::is_none")]
    pub is_deleted: Option<bool>,
    #[serde(rename = "isDeletedUser", skip_serializing_if = "Option::is_none")]
    pub is_deleted_user: Option<bool>,
    #[serde(rename = "isByAdmin", skip_serializing_if = "Option::is_none")]
    pub is_by_admin: Option<bool>,
    #[serde(rename = "isByModerator", skip_serializing_if = "Option::is_none")]
    pub is_by_moderator: Option<bool>,
    #[serde(rename = "isPinned", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<Option<bool>>,
    #[serde(rename = "isLocked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_locked: Option<Option<bool>>,
    #[serde(rename = "flagCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flag_count: Option<Option<i32>>,
    #[serde(rename = "displayLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<Option<String>>,
    #[serde(rename = "meta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Option<models::ApiCommentBaseMeta>>,
    #[serde(rename = "moderationGroupIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub moderation_group_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "feedbackIds", skip_serializing_if = "Option::is_none")]
    pub feedback_ids: Option<Vec<String>>,
}

impl UpdatableCommentParams {
    pub fn new() -> UpdatableCommentParams {
        UpdatableCommentParams {
            url_id: None,
            url_id_raw: None,
            url: None,
            page_title: None,
            user_id: None,
            commenter_email: None,
            commenter_name: None,
            commenter_link: None,
            comment: None,
            comment_html: None,
            parent_id: None,
            date: None,
            local_date_string: None,
            local_date_hours: None,
            votes: None,
            votes_up: None,
            votes_down: None,
            expire_at: None,
            verified: None,
            verified_date: None,
            notification_sent_for_parent: None,
            notification_sent_for_parent_tenant: None,
            reviewed: None,
            external_id: None,
            external_parent_id: None,
            avatar_src: None,
            is_spam: None,
            approved: None,
            is_deleted: None,
            is_deleted_user: None,
            is_by_admin: None,
            is_by_moderator: None,
            is_pinned: None,
            is_locked: None,
            flag_count: None,
            display_label: None,
            meta: None,
            moderation_group_ids: None,
            feedback_ids: None,
        }
    }
}

