/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserNotificationStatusResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "matchedCount", skip_serializing_if = "Option::is_none")]
    pub matched_count: Option<i64>,
    #[serde(rename = "modifiedCount", skip_serializing_if = "Option::is_none")]
    pub modified_count: Option<i64>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<Note>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "secondaryCode", skip_serializing_if = "Option::is_none")]
    pub secondary_code: Option<String>,
    #[serde(rename = "bannedUntil", skip_serializing_if = "Option::is_none")]
    pub banned_until: Option<i64>,
    #[serde(rename = "maxCharacterLength", skip_serializing_if = "Option::is_none")]
    pub max_character_length: Option<i32>,
    #[serde(rename = "translatedError", skip_serializing_if = "Option::is_none")]
    pub translated_error: Option<String>,
    #[serde(rename = "customConfig", skip_serializing_if = "Option::is_none")]
    pub custom_config: Option<Box<models::CustomConfigParameters>>,
}

impl UpdateUserNotificationStatusResponse {
    pub fn new(status: models::ApiStatus) -> UpdateUserNotificationStatusResponse {
        UpdateUserNotificationStatusResponse {
            status,
            matched_count: None,
            modified_count: None,
            note: None,
            reason: None,
            code: None,
            secondary_code: None,
            banned_until: None,
            max_character_length: None,
            translated_error: None,
            custom_config: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Note {
    #[serde(rename = "ignored-since-impersonated")]
    IgnoredSinceImpersonated,
    #[serde(rename = "demo-noop")]
    DemoNoop,
}

impl Default for Note {
    fn default() -> Note {
        Self::IgnoredSinceImpersonated
    }
}

