/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPresenceData {
    #[serde(rename = "urlIdWS", skip_serializing_if = "Option::is_none")]
    pub url_id_ws: Option<String>,
    #[serde(rename = "userIdWS", skip_serializing_if = "Option::is_none")]
    pub user_id_ws: Option<String>,
    #[serde(rename = "tenantIdWS", skip_serializing_if = "Option::is_none")]
    pub tenant_id_ws: Option<String>,
}

impl UserPresenceData {
    pub fn new() -> UserPresenceData {
        UserPresenceData {
            url_id_ws: None,
            user_id_ws: None,
            tenant_id_ws: None,
        }
    }
}

