/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserReactsResponse {
    #[serde(rename = "status")]
    pub status: models::ApiStatus,
    #[serde(rename = "reacts")]
    pub reacts: std::collections::HashMap<String, std::collections::HashMap<String, bool>>,
}

impl UserReactsResponse {
    pub fn new(status: models::ApiStatus, reacts: std::collections::HashMap<String, std::collections::HashMap<String, bool>>) -> UserReactsResponse {
        UserReactsResponse {
            status,
            reacts,
        }
    }
}

