/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserNotificationCount {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "count")]
    pub count: f64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "expireAt")]
    pub expire_at: String,
}

impl UserNotificationCount {
    pub fn new(_id: String, count: f64, created_at: String, expire_at: String) -> UserNotificationCount {
        UserNotificationCount {
            _id,
            count,
            created_at,
            expire_at,
        }
    }
}

