/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "websiteUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<Option<String>>,
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<String>,
    #[serde(rename = "pendingEmail", skip_serializing_if = "Option::is_none")]
    pub pending_email: Option<String>,
    #[serde(rename = "signUpDate")]
    pub sign_up_date: i64,
    #[serde(rename = "createdFromUrlId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_from_url_id: Option<Option<String>>,
    #[serde(rename = "createdFromTenantId", deserialize_with = "Option::deserialize")]
    pub created_from_tenant_id: Option<String>,
    #[serde(rename = "createdFromIpHashed")]
    pub created_from_ip_hashed: String,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "loginId")]
    pub login_id: String,
    #[serde(rename = "loginIdDate")]
    pub login_id_date: i64,
    #[serde(rename = "loginCount", skip_serializing_if = "Option::is_none")]
    pub login_count: Option<i32>,
    #[serde(rename = "optedInNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_notifications: Option<bool>,
    #[serde(rename = "optedInTenantNotifications", skip_serializing_if = "Option::is_none")]
    pub opted_in_tenant_notifications: Option<bool>,
    #[serde(rename = "hideAccountCode", skip_serializing_if = "Option::is_none")]
    pub hide_account_code: Option<bool>,
    #[serde(rename = "avatarSrc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_src: Option<Option<String>>,
    #[serde(rename = "isFastCommentsHelpRequestAdmin", skip_serializing_if = "Option::is_none")]
    pub is_fast_comments_help_request_admin: Option<bool>,
    #[serde(rename = "isHelpRequestAdmin", skip_serializing_if = "Option::is_none")]
    pub is_help_request_admin: Option<bool>,
    #[serde(rename = "isAccountOwner", skip_serializing_if = "Option::is_none")]
    pub is_account_owner: Option<bool>,
    #[serde(rename = "isAdminAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin_admin: Option<bool>,
    #[serde(rename = "isBillingAdmin", skip_serializing_if = "Option::is_none")]
    pub is_billing_admin: Option<bool>,
    #[serde(rename = "isAnalyticsAdmin", skip_serializing_if = "Option::is_none")]
    pub is_analytics_admin: Option<bool>,
    #[serde(rename = "isCustomizationAdmin", skip_serializing_if = "Option::is_none")]
    pub is_customization_admin: Option<bool>,
    #[serde(rename = "isManageDataAdmin", skip_serializing_if = "Option::is_none")]
    pub is_manage_data_admin: Option<bool>,
    #[serde(rename = "isCommentModeratorAdmin", skip_serializing_if = "Option::is_none")]
    pub is_comment_moderator_admin: Option<bool>,
    #[serde(rename = "isAPIAdmin", skip_serializing_if = "Option::is_none")]
    pub is_api_admin: Option<bool>,
    #[serde(rename = "moderatorIds", skip_serializing_if = "Option::is_none")]
    pub moderator_ids: Option<Vec<String>>,
    #[serde(rename = "isImpersonator", skip_serializing_if = "Option::is_none")]
    pub is_impersonator: Option<bool>,
    #[serde(rename = "isCouponManager", skip_serializing_if = "Option::is_none")]
    pub is_coupon_manager: Option<bool>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "digestEmailFrequency", skip_serializing_if = "Option::is_none")]
    pub digest_email_frequency: Option<models::DigestEmailFrequency>,
    #[serde(rename = "ignoredAddToMySiteMessages", skip_serializing_if = "Option::is_none")]
    pub ignored_add_to_my_site_messages: Option<bool>,
    #[serde(rename = "lastLoginDate", skip_serializing_if = "Option::is_none")]
    pub last_login_date: Option<String>,
    #[serde(rename = "displayLabel", skip_serializing_if = "Option::is_none")]
    pub display_label: Option<String>,
    #[serde(rename = "isProfileActivityPrivate", skip_serializing_if = "Option::is_none")]
    pub is_profile_activity_private: Option<bool>,
    #[serde(rename = "isProfileCommentsPrivate", skip_serializing_if = "Option::is_none")]
    pub is_profile_comments_private: Option<bool>,
    #[serde(rename = "isProfileDMDisabled", skip_serializing_if = "Option::is_none")]
    pub is_profile_dm_disabled: Option<bool>,
    #[serde(rename = "profileCommentApprovalMode", skip_serializing_if = "Option::is_none")]
    pub profile_comment_approval_mode: Option<f64>,
    #[serde(rename = "karma", skip_serializing_if = "Option::is_none")]
    pub karma: Option<f64>,
    #[serde(rename = "passwordHash", skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(rename = "averageTicketAckTimeMS", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub average_ticket_ack_time_ms: Option<Option<f64>>,
    #[serde(rename = "hasBlockedUsers", skip_serializing_if = "Option::is_none")]
    pub has_blocked_users: Option<bool>,
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(rename = "headerBackgroundSrc", skip_serializing_if = "Option::is_none")]
    pub header_background_src: Option<String>,
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "countryFlag", skip_serializing_if = "Option::is_none")]
    pub country_flag: Option<String>,
    #[serde(rename = "socialLinks", skip_serializing_if = "Option::is_none")]
    pub social_links: Option<Vec<String>>,
    #[serde(rename = "hasTwoFactor", skip_serializing_if = "Option::is_none")]
    pub has_two_factor: Option<bool>,
}

impl User {
    pub fn new(_id: String, username: String, email: Option<String>, sign_up_date: i64, created_from_tenant_id: Option<String>, created_from_ip_hashed: String, verified: bool, login_id: String, login_id_date: i64) -> User {
        User {
            _id,
            tenant_id: None,
            username,
            display_name: None,
            website_url: None,
            email,
            pending_email: None,
            sign_up_date,
            created_from_url_id: None,
            created_from_tenant_id,
            created_from_ip_hashed,
            verified,
            login_id,
            login_id_date,
            login_count: None,
            opted_in_notifications: None,
            opted_in_tenant_notifications: None,
            hide_account_code: None,
            avatar_src: None,
            is_fast_comments_help_request_admin: None,
            is_help_request_admin: None,
            is_account_owner: None,
            is_admin_admin: None,
            is_billing_admin: None,
            is_analytics_admin: None,
            is_customization_admin: None,
            is_manage_data_admin: None,
            is_comment_moderator_admin: None,
            is_api_admin: None,
            moderator_ids: None,
            is_impersonator: None,
            is_coupon_manager: None,
            locale: None,
            digest_email_frequency: None,
            ignored_add_to_my_site_messages: None,
            last_login_date: None,
            display_label: None,
            is_profile_activity_private: None,
            is_profile_comments_private: None,
            is_profile_dm_disabled: None,
            profile_comment_approval_mode: None,
            karma: None,
            password_hash: None,
            average_ticket_ack_time_ms: None,
            has_blocked_users: None,
            bio: None,
            header_background_src: None,
            country_code: None,
            country_flag: None,
            social_links: None,
            has_two_factor: None,
        }
    }
}

