/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoteResponse {
    #[serde(rename = "status")]
    pub status: Box<models::VoteResponseStatus>,
    #[serde(rename = "voteId", skip_serializing_if = "Option::is_none")]
    pub vote_id: Option<String>,
    #[serde(rename = "isVerified", skip_serializing_if = "Option::is_none")]
    pub is_verified: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::VoteResponseUser>>,
    #[serde(rename = "editKey", skip_serializing_if = "Option::is_none")]
    pub edit_key: Option<String>,
}

impl VoteResponse {
    pub fn new(status: models::VoteResponseStatus) -> VoteResponse {
        VoteResponse {
            status: Box::new(status),
            vote_id: None,
            is_verified: None,
            user: None,
            edit_key: None,
        }
    }
}

