/*
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::client::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoteDeleteResponse {
    #[serde(rename = "status")]
    pub status: Box<models::VoteDeleteResponseStatus>,
    #[serde(rename = "wasPendingVote", skip_serializing_if = "Option::is_none")]
    pub was_pending_vote: Option<bool>,
}

impl VoteDeleteResponse {
    pub fn new(status: models::VoteDeleteResponseStatus) -> VoteDeleteResponse {
        VoteDeleteResponse {
            status: Box::new(status),
            was_pending_vote: None,
        }
    }
}

